ALTER TABLE `tours` ADD `productCode` varchar(50);--> statement-breakpoint
ALTER TABLE `tours` ADD `departureCountry` varchar(100) DEFAULT '台灣';--> statement-breakpoint
ALTER TABLE `tours` ADD `departureCity` varchar(100) DEFAULT '桃園';--> statement-breakpoint
ALTER TABLE `tours` ADD `departureAirportCode` varchar(10);--> statement-breakpoint
ALTER TABLE `tours` ADD `departureAirportName` varchar(100);--> statement-breakpoint
ALTER TABLE `tours` ADD `destinationCountry` varchar(100) NOT NULL;--> statement-breakpoint
ALTER TABLE `tours` ADD `destinationCity` varchar(100) NOT NULL;--> statement-breakpoint
ALTER TABLE `tours` ADD `destinationRegion` varchar(100);--> statement-breakpoint
ALTER TABLE `tours` ADD `destinationAirportCode` varchar(10);--> statement-breakpoint
ALTER TABLE `tours` ADD `destinationAirportName` varchar(100);--> statement-breakpoint
ALTER TABLE `tours` ADD `nights` int;--> statement-breakpoint
ALTER TABLE `tours` ADD `priceUnit` varchar(20) DEFAULT '人/起';--> statement-breakpoint
ALTER TABLE `tours` ADD `outboundAirline` varchar(100);--> statement-breakpoint
ALTER TABLE `tours` ADD `outboundFlightNo` varchar(20);--> statement-breakpoint
ALTER TABLE `tours` ADD `outboundDepartureTime` varchar(10);--> statement-breakpoint
ALTER TABLE `tours` ADD `outboundArrivalTime` varchar(10);--> statement-breakpoint
ALTER TABLE `tours` ADD `outboundFlightDuration` varchar(20);--> statement-breakpoint
ALTER TABLE `tours` ADD `inboundAirline` varchar(100);--> statement-breakpoint
ALTER TABLE `tours` ADD `inboundFlightNo` varchar(20);--> statement-breakpoint
ALTER TABLE `tours` ADD `inboundDepartureTime` varchar(10);--> statement-breakpoint
ALTER TABLE `tours` ADD `inboundArrivalTime` varchar(10);--> statement-breakpoint
ALTER TABLE `tours` ADD `inboundFlightDuration` varchar(20);--> statement-breakpoint
ALTER TABLE `tours` ADD `hotelName` varchar(255);--> statement-breakpoint
ALTER TABLE `tours` ADD `hotelNights` int;--> statement-breakpoint
ALTER TABLE `tours` ADD `hotelLocation` varchar(255);--> statement-breakpoint
ALTER TABLE `tours` ADD `hotelDescription` text;--> statement-breakpoint
ALTER TABLE `tours` ADD `hotelFacilities` text;--> statement-breakpoint
ALTER TABLE `tours` ADD `hotelRoomType` varchar(100);--> statement-breakpoint
ALTER TABLE `tours` ADD `hotelRoomSize` varchar(50);--> statement-breakpoint
ALTER TABLE `tours` ADD `hotelCheckIn` varchar(10);--> statement-breakpoint
ALTER TABLE `tours` ADD `hotelCheckOut` varchar(10);--> statement-breakpoint
ALTER TABLE `tours` ADD `hotelSpecialOffers` text;--> statement-breakpoint
ALTER TABLE `tours` ADD `hotelImages` text;--> statement-breakpoint
ALTER TABLE `tours` ADD `hotelWebsite` varchar(512);--> statement-breakpoint
ALTER TABLE `tours` ADD `destinationDescription` text;--> statement-breakpoint
ALTER TABLE `tours` ADD `attractions` text;--> statement-breakpoint
ALTER TABLE `tours` ADD `dailyItinerary` text;--> statement-breakpoint
ALTER TABLE `tours` ADD `optionalTours` text;--> statement-breakpoint
ALTER TABLE `tours` ADD `tags` text;--> statement-breakpoint
ALTER TABLE `tours` ADD `promotionText` varchar(255);--> statement-breakpoint
ALTER TABLE `tours` ADD `galleryImages` text;--> statement-breakpoint
ALTER TABLE `tours` ADD `availableSeats` int;--> statement-breakpoint
ALTER TABLE `tours` ADD `specialReminders` text;--> statement-breakpoint
ALTER TABLE `tours` ADD `notes` text;--> statement-breakpoint
ALTER TABLE `tours` ADD `safetyGuidelines` text;--> statement-breakpoint
ALTER TABLE `tours` ADD `flightRules` text;--> statement-breakpoint
ALTER TABLE `tours` ADD `sourceUrl` varchar(1024);--> statement-breakpoint
ALTER TABLE `tours` ADD `isAutoGenerated` int DEFAULT 0;