CREATE TABLE `skillLearningHistory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sourceType` enum('tour','batch','scheduled','manual') NOT NULL,
	`sourceTourIds` text,
	`keywordSuggestions` text,
	`newSkillSuggestions` text,
	`identifiedTags` text,
	`totalKeywordsFound` int NOT NULL DEFAULT 0,
	`newKeywordsFound` int NOT NULL DEFAULT 0,
	`suggestionsAccepted` int NOT NULL DEFAULT 0,
	`suggestionsRejected` int NOT NULL DEFAULT 0,
	`skillsCreated` int NOT NULL DEFAULT 0,
	`processingTimeMs` int,
	`status` enum('pending','processing','completed','failed','partial') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`triggeredBy` enum('user','schedule','system') NOT NULL DEFAULT 'user',
	`triggeredByUserId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `skillLearningHistory_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `skillLearningSchedule` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`isEnabled` boolean NOT NULL DEFAULT true,
	`frequency` enum('daily','weekly','monthly') NOT NULL DEFAULT 'weekly',
	`dayOfWeek` int,
	`dayOfMonth` int,
	`hour` int NOT NULL DEFAULT 3,
	`minute` int NOT NULL DEFAULT 0,
	`learnFromNewTours` boolean NOT NULL DEFAULT true,
	`maxToursPerRun` int NOT NULL DEFAULT 10,
	`minTourAge` int NOT NULL DEFAULT 0,
	`autoApplyHighConfidence` boolean NOT NULL DEFAULT false,
	`autoApplyThreshold` decimal(3,2) DEFAULT '0.90',
	`notifyOnComplete` boolean NOT NULL DEFAULT true,
	`notifyOnNewSuggestions` boolean NOT NULL DEFAULT true,
	`lastRunAt` timestamp,
	`lastRunStatus` enum('success','failed','partial'),
	`lastRunHistoryId` int,
	`nextRunAt` timestamp,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `skillLearningSchedule_id` PRIMARY KEY(`id`)
);
