CREATE TABLE `learningAnalytics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`date` timestamp NOT NULL,
	`learningSessionsCount` int NOT NULL DEFAULT 0,
	`toursAnalyzed` int NOT NULL DEFAULT 0,
	`keywordsSuggested` int NOT NULL DEFAULT 0,
	`skillsSuggested` int NOT NULL DEFAULT 0,
	`keywordsAccepted` int NOT NULL DEFAULT 0,
	`keywordsRejected` int NOT NULL DEFAULT 0,
	`skillsApproved` int NOT NULL DEFAULT 0,
	`skillsRejected` int NOT NULL DEFAULT 0,
	`keywordAdoptionRate` decimal(5,4) DEFAULT '0.0000',
	`skillAdoptionRate` decimal(5,4) DEFAULT '0.0000',
	`sourceDistribution` text,
	`avgProcessingTimeMs` int,
	`totalProcessingTimeMs` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `learningAnalytics_id` PRIMARY KEY(`id`),
	CONSTRAINT `learningAnalytics_date_unique` UNIQUE(`date`)
);
--> statement-breakpoint
CREATE TABLE `skillReviewQueue` (
	`id` int AUTO_INCREMENT NOT NULL,
	`skillName` varchar(100) NOT NULL,
	`skillType` enum('technique','pattern','reference') NOT NULL,
	`category` varchar(100) NOT NULL,
	`keywords` text NOT NULL,
	`rules` text NOT NULL,
	`description` text,
	`outputLabels` text,
	`confidence` decimal(3,2) DEFAULT '0.80',
	`sourceType` enum('ai_learning','scheduled','manual') NOT NULL,
	`sourceTourId` int,
	`learningHistoryId` int,
	`status` enum('pending','approved','rejected','merged') NOT NULL DEFAULT 'pending',
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`createdSkillId` int,
	`priority` enum('low','medium','high') NOT NULL DEFAULT 'medium',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `skillReviewQueue_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tourStatistics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tourId` int NOT NULL,
	`viewCount` int NOT NULL DEFAULT 0,
	`uniqueViewCount` int NOT NULL DEFAULT 0,
	`favoriteCount` int NOT NULL DEFAULT 0,
	`shareCount` int NOT NULL DEFAULT 0,
	`inquiryCount` int NOT NULL DEFAULT 0,
	`bookingCount` int NOT NULL DEFAULT 0,
	`conversionRate` decimal(5,4) DEFAULT '0.0000',
	`totalRevenue` int NOT NULL DEFAULT 0,
	`popularityScore` decimal(10,4) DEFAULT '0.0000',
	`hasBeenLearned` boolean NOT NULL DEFAULT false,
	`lastLearnedAt` timestamp,
	`learningPriority` int NOT NULL DEFAULT 0,
	`lastViewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tourStatistics_id` PRIMARY KEY(`id`),
	CONSTRAINT `tourStatistics_tourId_unique` UNIQUE(`tourId`)
);
