CREATE TABLE `autoApprovalRules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ruleName` varchar(255) NOT NULL,
	`description` text,
	`ruleType` enum('confidence_threshold','source_type','keyword_count','skill_category','combined') NOT NULL,
	`conditions` text NOT NULL,
	`action` enum('auto_approve','auto_reject','flag_priority','notify_admin') NOT NULL,
	`priority` int NOT NULL DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`timesTriggered` int NOT NULL DEFAULT 0,
	`lastTriggeredAt` timestamp,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `autoApprovalRules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `skillPerformanceMetrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`skillId` int NOT NULL,
	`date` timestamp NOT NULL,
	`triggerCount` int NOT NULL DEFAULT 0,
	`uniqueUserCount` int NOT NULL DEFAULT 0,
	`successCount` int NOT NULL DEFAULT 0,
	`failureCount` int NOT NULL DEFAULT 0,
	`successRate` decimal(5,4) DEFAULT '0.0000',
	`positiveCount` int NOT NULL DEFAULT 0,
	`negativeCount` int NOT NULL DEFAULT 0,
	`satisfactionRate` decimal(5,4) DEFAULT '0.0000',
	`conversionCount` int NOT NULL DEFAULT 0,
	`conversionRate` decimal(5,4) DEFAULT '0.0000',
	`estimatedRevenue` int NOT NULL DEFAULT 0,
	`avgProcessingTimeMs` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `skillPerformanceMetrics_id` PRIMARY KEY(`id`),
	CONSTRAINT `skillPerformanceMetrics_skillId_date_unique` UNIQUE(`skillId`,`date`)
);
--> statement-breakpoint
CREATE TABLE `skillUsageLog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`skillId` int NOT NULL,
	`skillName` varchar(255) NOT NULL,
	`skillType` varchar(100) NOT NULL,
	`contextType` enum('chat','search','itinerary','content','classification') NOT NULL,
	`contextId` varchar(100),
	`inputText` text,
	`matchedKeywords` text,
	`outputResult` text,
	`userId` int,
	`sessionId` varchar(100),
	`wasSuccessful` boolean NOT NULL DEFAULT true,
	`errorMessage` text,
	`userFeedback` enum('positive','negative','none') NOT NULL DEFAULT 'none',
	`feedbackComment` text,
	`feedbackAt` timestamp,
	`ledToConversion` boolean NOT NULL DEFAULT false,
	`conversionType` enum('booking','inquiry','favorite','share','none') DEFAULT 'none',
	`conversionId` int,
	`conversionAt` timestamp,
	`processingTimeMs` int,
	`triggeredAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `skillUsageLog_id` PRIMARY KEY(`id`)
);
