import { Job } from "bullmq";
import {
  TourGenerationJobData,
  TourGenerationResult,
} from "./queue";
import { MasterAgent } from "./agents/masterAgent";
import { createTour } from "./db";
import { supplementImages } from "./services/unsplashService";

/**
 * Internal tour generation function called by worker
 * Uses multi-agent system to generate tour from URL
 * 
 * @param url - Source URL to scrape
 * @param userId - User ID who requested the generation
 * @param job - BullMQ job for progress tracking
 */
export async function generateTourFromUrlInternal(
  url: string,
  userId: number,
  job: Job<TourGenerationJobData, TourGenerationResult>
): Promise<TourGenerationResult> {
  console.log("[TourGenerator] Starting tour generation...");
  console.log("[TourGenerator] URL:", url);
  console.log("[TourGenerator] User ID:", userId);
  
  try {
    // Create Master Agent
    const masterAgent = new MasterAgent();
    
    // Execute tour generation with progress tracking
    const result = await masterAgent.execute(url, userId, (step, percentage) => {
      // Update job progress
      job.updateProgress({
        step,
        percentage,
        message: `Processing: ${step}`,
      });
    });
    
    if (!result.success || !result.data) {
      throw new Error(result.error || "Tour generation failed");
    }
    
    const tourData = result.data;
    
    // Supplement images if needed (minimum 6 images)
    await job.updateProgress({
      step: "supplementing_images",
      percentage: 90,
      message: "Checking and supplementing images...",
    });
    
    const destination = tourData.destinationCity || tourData.destinationCountry || "travel";
    
    // Parse featureImages (could be string or array)
    let currentImages: string[] = [];
    if (typeof tourData.featureImages === 'string') {
      try {
        currentImages = JSON.parse(tourData.featureImages);
      } catch {
        currentImages = [];
      }
    } else if (Array.isArray(tourData.featureImages)) {
      currentImages = tourData.featureImages;
    }
    
    const supplementedImages = await supplementImages(currentImages, destination, 6);
    
    console.log(`[TourGenerator] Image supplement: ${currentImages.length} -> ${supplementedImages.length}`);
    
    // Update tourData with supplemented images (convert to JSON string)
    tourData.featureImages = JSON.stringify(supplementedImages);
    
    // Save to database
    await job.updateProgress({
      step: "saving",
      percentage: 95,
      message: "Saving tour to database...",
    });
    
    const tour = await createTour({
      title: tourData.title,
      description: tourData.description,
      productCode: tourData.productCode,
      destinationCountry: tourData.destinationCountry,
      destinationCity: tourData.destinationCity,
      departureCity: tourData.departureCity,
      duration: tourData.days,
      nights: tourData.nights,
      price: tourData.price,
      destination: tourData.destinationCity || tourData.destinationCountry, // Legacy field for compatibility
      tags: JSON.stringify(tourData.tags),
      
      // Hero section
      heroImage: tourData.heroImage,
      heroImageAlt: tourData.heroImageAlt,
      heroSubtitle: tourData.heroSubtitle,
      
      // Color theme and features
      colorTheme: tourData.colorTheme,
      keyFeatures: tourData.keyFeatures,
      poeticContent: tourData.poeticContent,
      featureImages: tourData.featureImages,
      highlights: tourData.highlights,
      
      // Detailed content from agents (CRITICAL: These fields were missing!)
      itineraryDetailed: tourData.itineraryDetailed, // 每日行程
      costExplanation: tourData.costExplanation, // 費用說明
      noticeDetailed: tourData.noticeDetailed, // 注意事項
      hotels: tourData.hotels, // 飯店介紹
      meals: tourData.meals, // 餐飲介紹
      flights: tourData.flights, // 航班資訊
      
      // Additional fields
      status: "active",
      featured: 0, // 0 = false, 1 = true
      promotionText: "",
      
      // Metadata
      createdBy: userId,
      sourceUrl: tourData.sourceUrl,
      originalityScore: tourData.originalityScore.toString(), // Convert to string for decimal field
      isAutoGenerated: 1, // Mark as auto-generated
    });
    
    console.log("[TourGenerator] Tour saved to database with ID:", tour.id);
    
    await job.updateProgress({
      step: "completed",
      percentage: 100,
      message: "Tour generation completed!",
    });
    
    return {
      success: true,
      tourId: tour.id,
    };
  } catch (error) {
    console.error("[TourGenerator] Error:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}
