import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import DeparturesManagement from "./DeparturesManagement";
import { Calendar, Edit, Eye, EyeOff, ExternalLink, Loader2, Plus, RefreshCw, Search, Sparkles, Star, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type TourFormData = {
  title: string;
  destination: string;
  destinationCountry: string;
  destinationCity: string;
  description: string;
  duration: number;
  price: number;
  imageUrl?: string;
  category: "group" | "custom" | "package" | "cruise" | "theme";
  status: "active" | "inactive" | "soldout";
  featured: number;
  maxParticipants?: number;
  highlights?: string;
  includes?: string;
  excludes?: string;
};

export default function ToursTab() {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [isBatchDeleteDialogOpen, setIsBatchDeleteDialogOpen] = useState(false);
  const [isAutoGenerateDialogOpen, setIsAutoGenerateDialogOpen] = useState(false);
  const [isPreviewDialogOpen, setIsPreviewDialogOpen] = useState(false);
  const [isDeparturesDialogOpen, setIsDeparturesDialogOpen] = useState(false);
  const [selectedTourForDepartures, setSelectedTourForDepartures] = useState<{id: number, title: string} | null>(null);
  const [autoGenerateUrl, setAutoGenerateUrl] = useState("");
  const [generatedTourData, setGeneratedTourData] = useState<any>(null);
  const [extractionStep, setExtractionStep] = useState<number>(0); // 0: 未開始, 1: 抓取網頁, 2: 解析內容, 3: AI 分析, 4: 預覽準備完成
  const [selectedTourId, setSelectedTourId] = useState<number | null>(null);
  const [selectedTourIds, setSelectedTourIds] = useState<number[]>([]);
  const [statusFilter, setStatusFilter] = useState<"all" | "active" | "inactive">("all");
  const [featuredFilter, setFeaturedFilter] = useState<"all" | "featured" | "normal">("all");
  const [searchKeyword, setSearchKeyword] = useState<string>("");
  const [sortBy, setSortBy] = useState<"default" | "price-asc" | "price-desc" | "duration-asc" | "duration-desc" | "date-asc" | "date-desc">("default");
  const [formData, setFormData] = useState<TourFormData>({
    title: "",
    destination: "",
    destinationCountry: "",
    destinationCity: "",
    description: "",
    duration: 1,
    price: 0,
    imageUrl: "",
    category: "group",
    status: "active",
    featured: 0,
    maxParticipants: undefined,
    highlights: "",
    includes: "",
    excludes: "",
  });

  const utils = trpc.useUtils();
  const { data: tours, isLoading: toursLoading } = trpc.tours.list.useQuery();
  
  const createTourMutation = trpc.tours.create.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      setIsCreateDialogOpen(false);
      resetForm();
      toast.success("行程已成功建立");
    },
    onError: (error) => {
      toast.error(`建立失敗：${error.message}`);
    },
  });

  const updateTourMutation = trpc.tours.update.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      setIsEditDialogOpen(false);
      resetForm();
      toast.success("行程已成功更新");
    },
    onError: (error) => {
      toast.error(`更新失敗：${error.message}`);
    },
  });

  const deleteTourMutation = trpc.tours.delete.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      setIsDeleteDialogOpen(false);
      setSelectedTourId(null);
      toast.success("行程已成功刪除");
    },
    onError: (error) => {
      toast.error(`刪除失敗：${error.message}`);
    },
  });

  const batchDeleteToursMutation = trpc.tours.batchDelete.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      setIsBatchDeleteDialogOpen(false);
      setSelectedTourIds([]);
      toast.success("已成功刪除所選行程");
    },
    onError: (error) => {
      toast.error(`批量刪除失敗：${error.message}`);
    },
  });

  const toggleStatusMutation = trpc.tours.toggleStatus.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      toast.success("狀態已更新");
    },
    onError: (error) => {
      toast.error(`狀態更新失敗：${error.message}`);
    },
  });

  const toggleFeaturedMutation = trpc.tours.toggleFeatured.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      toast.success("精選狀態已更新");
    },
    onError: (error) => {
      toast.error(`精選狀態更新失敗：${error.message}`);
    },
  });

  // 完整生成 mutation (使用 MasterAgent) - 預覽模式
  const autoGenerateCompleteMutation = trpc.tours.autoGenerateComplete.useMutation({
    onSuccess: (result) => {
      setExtractionStep(4); // 預覽準備完成
      if (result.success && result.data) {
        // 設置生成的資料並打開預覽對話框
        setGeneratedTourData(result.data);
        setIsAutoGenerateDialogOpen(false);
        setIsPreviewDialogOpen(true);
        toast.success(
          result.message || "行程預覽已生成！",
          {
            description: "請檢查生成的內容，確認無誤後再儲存",
            duration: 5000,
          }
        );
      }
    },
    onError: (error) => {
      setExtractionStep(0);
      console.error("[AutoGenerateComplete] Error:", error);
      toast.error(`生成失敗：${error.message}`, {
        description: "請檢查網址是否正確並重試",
        duration: 5000,
      });
    },
  });

  // 從預覽儲存 mutation
  const saveFromPreviewMutation = trpc.tours.saveFromPreview.useMutation({
    onSuccess: (result) => {
      utils.tours.list.invalidate();
      setIsPreviewDialogOpen(false);
      setGeneratedTourData(null);
      setAutoGenerateUrl("");
      setExtractionStep(0);
      toast.success(
        result.message || "行程已成功儲存！",
        {
          description: `行程 ID: ${result.tourId}`,
          duration: 5000,
        }
      );
    },
    onError: (error) => {
      toast.error(`儲存失敗：${error.message}`);
    },
  });

  const handleAutoGenerate = () => {
    if (!autoGenerateUrl.trim()) {
      toast.error("請輸入行程網址");
      return;
    }
    setExtractionStep(1); // 開始抓取網頁
    
    // 完整生成模式 - 使用 MasterAgent (預覽模式)
    // 模擬進度更新 (完整生成需要更長時間)
    setTimeout(() => setExtractionStep(2), 5000); // 5秒後進入解析內容
    setTimeout(() => setExtractionStep(3), 10000); // 10秒後進入 AI 分析
    
    // 使用預覽模式，不自動儲存
    autoGenerateCompleteMutation.mutate({ 
      url: autoGenerateUrl,
      previewOnly: true,
      autoSave: false,
    });
  };

  const handleConfirmGeneratedTour = () => {
    if (generatedTourData) {
      // 使用 saveFromPreview mutation 儲存
      saveFromPreviewMutation.mutate({ tourData: generatedTourData });
    }
  };

  const handleRegenerate = () => {
    // 關閉預覽對話框，重新打開生成對話框
    setIsPreviewDialogOpen(false);
    setGeneratedTourData(null);
    setIsAutoGenerateDialogOpen(true);
    setExtractionStep(0);
  };

  const resetForm = () => {
    setFormData({
      title: "",
      destination: "",
      destinationCountry: "",
      destinationCity: "",
      description: "",
      duration: 1,
      price: 0,
      imageUrl: "",
      category: "group",
      status: "active",
      featured: 0,
      maxParticipants: undefined,
      highlights: "",
      includes: "",
      excludes: "",
    });
  };

  const handleCreate = () => {
    if (!formData.title || !formData.destination) {
      toast.error("請填寫必填欄位");
      return;
    }
    createTourMutation.mutate(formData);
  };

  const handleEdit = (tourId: number) => {
    const tour = tours?.find((t) => t.id === tourId);
    if (tour) {
      setSelectedTourId(tourId);
      setFormData({
        title: tour.title,
        destination: tour.destination,
        destinationCountry: tour.destinationCountry || "",
        destinationCity: tour.destinationCity || "",
        description: tour.description || "",
        duration: tour.duration,
        price: tour.price,
        imageUrl: tour.imageUrl || "",
        category: tour.category as any,
        status: tour.status as any,
        featured: tour.featured || 0,
        maxParticipants: tour.maxParticipants || undefined,
        highlights: tour.highlights || "",
        includes: tour.includes || "",
        excludes: tour.excludes || "",
      });
      setIsEditDialogOpen(true);
    }
  };

  const handleUpdate = () => {
    if (selectedTourId) {
      updateTourMutation.mutate({
        id: selectedTourId,
        ...formData,
      });
    }
  };

  const handleDelete = (tourId: number) => {
    setSelectedTourId(tourId);
    setIsDeleteDialogOpen(true);
  };

  const confirmDelete = () => {
    if (selectedTourId) {
      deleteTourMutation.mutate({ id: selectedTourId });
    }
  };

  const handleBatchDelete = () => {
    if (selectedTourIds.length === 0) {
      toast.error("請先選擇要刪除的行程");
      return;
    }
    setIsBatchDeleteDialogOpen(true);
  };

  const confirmBatchDelete = () => {
    batchDeleteToursMutation.mutate({ ids: selectedTourIds });
  };

  const toggleSelectTour = (tourId: number) => {
    setSelectedTourIds((prev) =>
      prev.includes(tourId)
        ? prev.filter((id) => id !== tourId)
        : [...prev, tourId]
    );
  };

  const toggleSelectAll = () => {
    if (filteredTours && selectedTourIds.length === filteredTours.length) {
      setSelectedTourIds([]);
    } else if (filteredTours) {
      setSelectedTourIds(filteredTours.map((t) => t.id));
    }
  };

  // Filter and sort tours
  const filteredTours = tours
    ?.filter((tour) => {
      if (statusFilter !== "all" && tour.status !== statusFilter) return false;
      if (featuredFilter === "featured" && tour.featured !== 1) return false;
      if (featuredFilter === "normal" && tour.featured === 1) return false;
      if (searchKeyword) {
        const keyword = searchKeyword.toLowerCase();
        return (
          tour.title.toLowerCase().includes(keyword) ||
          tour.destination.toLowerCase().includes(keyword) ||
          (tour.destinationCountry?.toLowerCase().includes(keyword)) ||
          (tour.destinationCity?.toLowerCase().includes(keyword))
        );
      }
      return true;
    })
    .sort((a, b) => {
      switch (sortBy) {
        case "price-asc":
          return a.price - b.price;
        case "price-desc":
          return b.price - a.price;
        case "duration-asc":
          return a.duration - b.duration;
        case "duration-desc":
          return b.duration - a.duration;
        case "date-asc":
          return new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime();
        case "date-desc":
          return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
        default:
          return 0;
      }
    });

  const getExtractionStepText = (step: number) => {
    switch (step) {
      case 1:
        return "正在抓取網頁內容...";
      case 2:
        return "正在解析行程資訊...";
      case 3:
        return "AI 正在分析並生成內容...";
      case 4:
        return "預覽準備完成！";
      default:
        return "";
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">行程管理</h2>
          <p className="text-gray-500 text-sm mt-1">管理所有旅遊行程</p>
        </div>
        <div className="flex gap-2">
          {selectedTourIds.length > 0 && (
            <Button
              variant="destructive"
              onClick={handleBatchDelete}
              className="rounded-full"
            >
              <Trash2 className="h-4 w-4 mr-2" />
              刪除所選 ({selectedTourIds.length})
            </Button>
          )}
          <Button
            variant="outline"
            onClick={() => setIsAutoGenerateDialogOpen(true)}
            className="rounded-full border-purple-300 text-purple-700 hover:bg-purple-50"
          >
            <Sparkles className="h-4 w-4 mr-2" />
            AI 自動生成
          </Button>
          <Button
            onClick={() => setIsCreateDialogOpen(true)}
            className="bg-black text-white hover:bg-gray-800 rounded-full"
          >
            <Plus className="h-4 w-4 mr-2" />
            新增行程
          </Button>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-4 items-center bg-gray-50 p-4 rounded-2xl">
        <div className="flex-1 min-w-[200px]">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
            <Input
              placeholder="搜尋行程..."
              value={searchKeyword}
              onChange={(e) => setSearchKeyword(e.target.value)}
              className="pl-10 rounded-full"
            />
          </div>
        </div>
        <Select value={statusFilter} onValueChange={(v: any) => setStatusFilter(v)}>
          <SelectTrigger className="w-[140px] rounded-full">
            <SelectValue placeholder="狀態" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">全部狀態</SelectItem>
            <SelectItem value="active">上架中</SelectItem>
            <SelectItem value="inactive">已下架</SelectItem>
          </SelectContent>
        </Select>
        <Select value={featuredFilter} onValueChange={(v: any) => setFeaturedFilter(v)}>
          <SelectTrigger className="w-[140px] rounded-full">
            <SelectValue placeholder="精選" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">全部</SelectItem>
            <SelectItem value="featured">精選行程</SelectItem>
            <SelectItem value="normal">一般行程</SelectItem>
          </SelectContent>
        </Select>
        <Select value={sortBy} onValueChange={(v: any) => setSortBy(v)}>
          <SelectTrigger className="w-[160px] rounded-full">
            <SelectValue placeholder="排序" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="default">預設排序</SelectItem>
            <SelectItem value="price-asc">價格低到高</SelectItem>
            <SelectItem value="price-desc">價格高到低</SelectItem>
            <SelectItem value="duration-asc">天數少到多</SelectItem>
            <SelectItem value="duration-desc">天數多到少</SelectItem>
            <SelectItem value="date-desc">最新建立</SelectItem>
            <SelectItem value="date-asc">最早建立</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* Tours Table */}
      <div className="bg-white rounded-2xl border border-gray-200 overflow-hidden">
        {toursLoading ? (
          <div className="p-8 text-center">
            <Loader2 className="h-8 w-8 animate-spin mx-auto text-gray-400" />
            <p className="text-gray-500 mt-2">載入中...</p>
          </div>
        ) : filteredTours && filteredTours.length > 0 ? (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50 border-b border-gray-200">
                <tr>
                  <th className="px-4 py-3 text-left">
                    <Checkbox
                      checked={filteredTours.length > 0 && selectedTourIds.length === filteredTours.length}
                      onCheckedChange={toggleSelectAll}
                    />
                  </th>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">行程</th>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">目的地</th>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">天數</th>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">價格</th>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">狀態</th>
                  <th className="px-4 py-3 text-right text-xs font-semibold text-gray-600 uppercase tracking-wider">操作</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {filteredTours.map((tour) => (
                  <tr key={tour.id} className="hover:bg-gray-50 transition-colors">
                    <td className="px-4 py-4">
                      <Checkbox
                        checked={selectedTourIds.includes(tour.id)}
                        onCheckedChange={() => toggleSelectTour(tour.id)}
                      />
                    </td>
                    <td className="px-4 py-4">
                      <div className="flex items-center gap-3">
                        {tour.imageUrl ? (
                          <img
                            src={tour.imageUrl}
                            alt={tour.title}
                            className="h-12 w-16 object-cover rounded-lg"
                          />
                        ) : (
                          <div className="h-12 w-16 bg-gray-200 rounded-lg flex items-center justify-center">
                            <span className="text-gray-400 text-xs">無圖片</span>
                          </div>
                        )}
                        <div>
                          <p className="font-medium text-gray-900 line-clamp-1">{tour.title}</p>
                          {tour.isAutoGenerated === 1 && (
                            <span className="inline-flex items-center gap-1 text-xs text-purple-600">
                              <Sparkles className="h-3 w-3" />
                              AI 生成
                            </span>
                          )}
                        </div>
                      </div>
                    </td>
                    <td className="px-4 py-4 text-sm text-gray-600">
                      {tour.destinationCountry && tour.destinationCity
                        ? `${tour.destinationCountry} / ${tour.destinationCity}`
                        : tour.destination}
                    </td>
                    <td className="px-4 py-4 text-sm text-gray-600">{tour.duration} 天</td>
                    <td className="px-4 py-4 text-sm font-medium text-gray-900">
                      NT$ {tour.price.toLocaleString()}
                    </td>
                    <td className="px-4 py-4">
                      <span
                        className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                          tour.status === "active"
                            ? "bg-green-100 text-green-800"
                            : "bg-gray-100 text-gray-800"
                        }`}
                      >
                        {tour.status === "active" ? "上架中" : "已下架"}
                      </span>
                    </td>
                    <td className="px-4 py-4">
                      <div className="flex items-center justify-end gap-1">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => toggleStatusMutation.mutate({ id: tour.id })}
                          disabled={toggleStatusMutation.isPending}
                          className="h-9 w-9 p-0 rounded-full hover:bg-gray-100 transition-colors"
                          title={tour.status === "active" ? "下架" : "上架"}
                        >
                          {tour.status === "active" ? (
                            <EyeOff className="h-4 w-4" />
                          ) : (
                            <Eye className="h-4 w-4" />
                          )}
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => toggleFeaturedMutation.mutate({ id: tour.id })}
                          className={`h-9 w-9 p-0 rounded-full transition-colors ${
                            tour.featured === 1
                              ? "text-yellow-500 hover:bg-yellow-50"
                              : "hover:bg-gray-100"
                          }`}
                          title={tour.featured === 1 ? "取消精選" : "設為精選"}
                          disabled={toggleFeaturedMutation.isPending}
                        >
                          <Star className={`h-4 w-4 ${tour.featured === 1 ? "fill-current" : ""}`} />
                        </Button>
                        <div className="w-px h-6 bg-gray-200 mx-1"></div>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => {
                            setSelectedTourForDepartures({id: tour.id, title: tour.title});
                            setIsDeparturesDialogOpen(true);
                          }}
                          className="h-9 w-9 p-0 rounded-full hover:bg-gray-100 transition-colors"
                          title="管理出發日期"
                        >
                          <Calendar className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleEdit(tour.id)}
                          className="h-9 w-9 p-0 rounded-full hover:bg-blue-50 hover:text-blue-600 transition-colors"
                          title="編輯行程"
                        >
                          <Edit className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleDelete(tour.id)}
                          className="h-9 w-9 p-0 rounded-full text-red-600 hover:bg-red-50 hover:text-red-700 transition-colors"
                          title="刪除行程"
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : tours && tours.length > 0 ? (
          <div className="p-8 text-center">
            <p className="text-gray-600">沒有符合篩選條件的行程</p>
            <Button
              variant="link"
              onClick={() => {
                setStatusFilter("all");
                setFeaturedFilter("all");
              }}
              className="text-primary mt-2"
            >
              清除篩選條件
            </Button>
          </div>
        ) : (
          <div className="p-8 text-center">
            <p className="text-gray-600">尚無行程資料</p>
          </div>
        )}
      </div>

      {/* Create Dialog */}
      <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto rounded-3xl">
          <DialogHeader>
            <DialogTitle>新增行程</DialogTitle>
            <DialogDescription>填寫以下資訊以建立新的旅遊行程</DialogDescription>
          </DialogHeader>
          <TourForm formData={formData} setFormData={setFormData} />
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsCreateDialogOpen(false)}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              onClick={handleCreate}
              disabled={createTourMutation.isPending}
              className="bg-black text-white hover:bg-gray-800 rounded-full"
            >
              {createTourMutation.isPending ? "建立中..." : "建立"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Edit Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto rounded-3xl">
          <DialogHeader>
            <DialogTitle>編輯行程</DialogTitle>
            <DialogDescription>修改行程資訊</DialogDescription>
          </DialogHeader>
          <TourForm formData={formData} setFormData={setFormData} />
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsEditDialogOpen(false)}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              onClick={handleUpdate}
              disabled={updateTourMutation.isPending}
              className="bg-black text-white hover:bg-gray-800 rounded-full"
            >
              {updateTourMutation.isPending ? "更新中..." : "更新"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Dialog */}
      <Dialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <DialogContent className="rounded-3xl">
          <DialogHeader>
            <DialogTitle>確認刪除</DialogTitle>
            <DialogDescription>
              確定要刪除這個行程嗎？此操作無法復原。
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsDeleteDialogOpen(false)}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              variant="destructive"
              onClick={confirmDelete}
              disabled={deleteTourMutation.isPending}
              className="rounded-full"
            >
              {deleteTourMutation.isPending ? "刪除中..." : "確認刪除"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Batch Delete Dialog */}
      <Dialog open={isBatchDeleteDialogOpen} onOpenChange={setIsBatchDeleteDialogOpen}>
        <DialogContent className="rounded-3xl">
          <DialogHeader>
            <DialogTitle>確認批量刪除</DialogTitle>
            <DialogDescription>
              確定要刪除所選的 {selectedTourIds.length} 個行程嗎？此操作無法復原。
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsBatchDeleteDialogOpen(false)}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              variant="destructive"
              onClick={confirmBatchDelete}
              disabled={batchDeleteToursMutation.isPending}
              className="rounded-full"
            >
              {batchDeleteToursMutation.isPending ? "刪除中..." : "確認刪除"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Auto Generate Dialog */}
      <Dialog open={isAutoGenerateDialogOpen} onOpenChange={(open) => {
        if (!open && !autoGenerateCompleteMutation.isPending) {
          setIsAutoGenerateDialogOpen(false);
          setAutoGenerateUrl("");
          setExtractionStep(0);
        }
      }}>
        <DialogContent className="max-w-lg rounded-3xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-purple-600" />
              AI 自動生成行程
            </DialogTitle>
            <DialogDescription>
              輸入旅遊行程網址，AI 將自動提取並生成行程資訊
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="url">行程網址</Label>
              <Input
                id="url"
                placeholder="https://www.liontravel.com/..."
                value={autoGenerateUrl}
                onChange={(e) => setAutoGenerateUrl(e.target.value)}
                disabled={autoGenerateCompleteMutation.isPending}
                className="rounded-full"
              />
              <p className="text-xs text-gray-500">
                支援雄獅旅遊、可樂旅遊等主流旅行社網站
              </p>
            </div>
            
            {/* Progress indicator */}
            {extractionStep > 0 && extractionStep < 4 && (
              <div className="bg-purple-50 rounded-2xl p-4">
                <div className="flex items-center gap-3">
                  <Loader2 className="h-5 w-5 animate-spin text-purple-600" />
                  <div>
                    <p className="font-medium text-purple-900">{getExtractionStepText(extractionStep)}</p>
                    <p className="text-sm text-purple-600">
                      完整生成模式：包含 Hero 圖片、配色主題、詳細行程等
                    </p>
                  </div>
                </div>
                <div className="mt-3 h-2 bg-purple-200 rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-purple-600 transition-all duration-500"
                    style={{ width: `${(extractionStep / 4) * 100}%` }}
                  />
                </div>
                <p className="text-xs text-purple-500 mt-2">
                  預計需要 60-90 秒，請耐心等候...
                </p>
              </div>
            )}
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setIsAutoGenerateDialogOpen(false);
                setAutoGenerateUrl("");
                setExtractionStep(0);
              }}
              disabled={autoGenerateCompleteMutation.isPending}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              onClick={handleAutoGenerate}
              disabled={autoGenerateCompleteMutation.isPending || !autoGenerateUrl.trim()}
              className="bg-purple-600 text-white hover:bg-purple-700 rounded-full"
            >
              {autoGenerateCompleteMutation.isPending ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  生成中...
                </>
              ) : (
                <>
                  <Sparkles className="h-4 w-4 mr-2" />
                  開始生成
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Departures Management Dialog */}
      <Dialog open={isDeparturesDialogOpen} onOpenChange={setIsDeparturesDialogOpen}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto rounded-3xl">
          <DialogHeader>
            <DialogTitle>出發日期管理</DialogTitle>
            <DialogDescription>
              {selectedTourForDepartures?.title}
            </DialogDescription>
          </DialogHeader>
          {selectedTourForDepartures && (
            <DeparturesManagement tourId={selectedTourForDepartures.id} />
          )}
        </DialogContent>
      </Dialog>

      {/* Preview Generated Tour Dialog - Enhanced */}
      <Dialog open={isPreviewDialogOpen} onOpenChange={setIsPreviewDialogOpen}>
        <DialogContent className="max-w-5xl max-h-[90vh] overflow-y-auto rounded-3xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-purple-600" />
              行程預覽
            </DialogTitle>
            <DialogDescription>
              請檢查 AI 自動生成的行程資訊，確認無誤後再儲存
            </DialogDescription>
          </DialogHeader>
          {generatedTourData && (
            <div className="grid gap-6 py-4">
              {/* Hero Image Preview */}
              {generatedTourData.heroImage && (
                <div className="relative rounded-2xl overflow-hidden">
                  <img 
                    src={generatedTourData.heroImage} 
                    alt="Hero" 
                    className="w-full h-48 object-cover"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
                  <div className="absolute bottom-4 left-4 right-4 text-white">
                    <h3 className="text-xl font-bold">{generatedTourData.poeticTitle || generatedTourData.title}</h3>
                    <p className="text-sm opacity-90 mt-1">{generatedTourData.heroSubtitle || generatedTourData.promotionText}</p>
                  </div>
                </div>
              )}

              {/* Basic Info */}
              <div className="bg-purple-50 rounded-2xl p-4">
                <h3 className="font-semibold text-purple-900 mb-3">基本資訊</h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-gray-500">標題：</span>
                    <span className="ml-2 font-medium">{generatedTourData.title}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">產品代碼：</span>
                    <span className="ml-2">{generatedTourData.productCode || '-'}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">促銷文字：</span>
                    <span className="ml-2 text-red-600">{generatedTourData.promotionText || '-'}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">天數：</span>
                    <span className="ml-2">{generatedTourData.duration} 天 {generatedTourData.nights || (generatedTourData.duration - 1)} 晚</span>
                  </div>
                  <div>
                    <span className="text-gray-500">價格：</span>
                    <span className="ml-2 font-bold text-lg text-green-600">NT$ {generatedTourData.price?.toLocaleString()}</span>
                  </div>
                </div>
              </div>

              {/* Location Info */}
              <div className="bg-blue-50 rounded-2xl p-4">
                <h3 className="font-semibold text-blue-900 mb-3">地點資訊</h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-gray-500">出發國家/城市：</span>
                    <span className="ml-2">{generatedTourData.departureCountry} / {generatedTourData.departureCity}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">出發機場：</span>
                    <span className="ml-2">{generatedTourData.departureAirportCode} {generatedTourData.departureAirportName}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">目的地國家/城市：</span>
                    <span className="ml-2 font-medium">{generatedTourData.destinationCountry} / {generatedTourData.destinationCity}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">目的地機場：</span>
                    <span className="ml-2">{generatedTourData.destinationAirportCode} {generatedTourData.destinationAirportName}</span>
                  </div>
                </div>
              </div>

              {/* Itinerary Preview */}
              {generatedTourData.itineraryDetailed && (
                <div className="bg-amber-50 rounded-2xl p-4">
                  <h3 className="font-semibold text-amber-900 mb-3">每日行程預覽</h3>
                  <div className="space-y-2 text-sm max-h-40 overflow-y-auto">
                    {(() => {
                      try {
                        const itinerary = JSON.parse(generatedTourData.itineraryDetailed);
                        return itinerary.slice(0, 3).map((day: any, index: number) => (
                          <div key={index} className="flex gap-2">
                            <span className="font-medium text-amber-700">Day {day.day || index + 1}:</span>
                            <span className="text-gray-700">{day.title || day.description?.substring(0, 50) || '-'}</span>
                          </div>
                        ));
                      } catch {
                        return <p className="text-gray-500">無法解析行程資料</p>;
                      }
                    })()}
                    {(() => {
                      try {
                        const itinerary = JSON.parse(generatedTourData.itineraryDetailed);
                        if (itinerary.length > 3) {
                          return <p className="text-amber-600 text-xs">... 還有 {itinerary.length - 3} 天行程</p>;
                        }
                      } catch {
                        return null;
                      }
                    })()}
                  </div>
                </div>
              )}

              {/* Cost Explanation Preview */}
              {generatedTourData.costExplanation && (
                <div className="bg-green-50 rounded-2xl p-4">
                  <h3 className="font-semibold text-green-900 mb-3">費用說明預覽</h3>
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    {(() => {
                      try {
                        const cost = JSON.parse(generatedTourData.costExplanation);
                        return (
                          <>
                            <div>
                              <span className="text-gray-500">包含項目：</span>
                              <span className="ml-2">{cost.includes?.length || 0} 項</span>
                            </div>
                            <div>
                              <span className="text-gray-500">不包含項目：</span>
                              <span className="ml-2">{cost.excludes?.length || 0} 項</span>
                            </div>
                          </>
                        );
                      } catch {
                        return <p className="text-gray-500">無法解析費用資料</p>;
                      }
                    })()}
                  </div>
                </div>
              )}

              {/* Description */}
              <div className="bg-gray-50 rounded-2xl p-4">
                <h3 className="font-semibold text-gray-900 mb-3">行程描述</h3>
                <p className="text-sm text-gray-700 whitespace-pre-wrap line-clamp-4">{generatedTourData.description}</p>
              </div>

              {/* Source URL */}
              {isAdmin && generatedTourData.sourceUrl && (
                <div className="text-xs text-gray-400 flex items-center gap-2">
                  <ExternalLink className="h-3 w-3" />
                  來源：
                  <a 
                    href={generatedTourData.sourceUrl} 
                    target="_blank" 
                    rel="noopener noreferrer" 
                    className="text-blue-500 hover:underline"
                  >
                    {generatedTourData.sourceUrl}
                  </a>
                </div>
              )}

              {/* Execution Report */}
              {generatedTourData.executionReport && (
                <details className="text-xs text-gray-400">
                  <summary className="cursor-pointer hover:text-gray-600">查看執行報告</summary>
                  <pre className="mt-2 p-2 bg-gray-100 rounded-lg overflow-x-auto whitespace-pre-wrap">
                    {generatedTourData.executionReport}
                  </pre>
                </details>
              )}
            </div>
          )}
          <DialogFooter className="flex gap-2">
            <Button
              variant="outline"
              onClick={() => {
                setIsPreviewDialogOpen(false);
                setGeneratedTourData(null);
                setAutoGenerateUrl("");
                setExtractionStep(0);
              }}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              variant="outline"
              onClick={handleRegenerate}
              className="rounded-full border-purple-300 text-purple-700 hover:bg-purple-50"
            >
              <RefreshCw className="h-4 w-4 mr-2" />
              重新生成
            </Button>
            <Button
              onClick={handleConfirmGeneratedTour}
              disabled={saveFromPreviewMutation.isPending}
              className="bg-purple-600 text-white hover:bg-purple-700 rounded-full"
            >
              {saveFromPreviewMutation.isPending ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  儲存中...
                </>
              ) : (
                "確認儲存"
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// Tour Form Component
function TourForm({
  formData,
  setFormData,
}: {
  formData: TourFormData;
  setFormData: React.Dispatch<React.SetStateAction<TourFormData>>;
}) {
  return (
    <div className="grid gap-6 py-4">
      {/* 基本資訊區塊 */}
      <div className="space-y-4">
        <div className="flex items-center gap-2 pb-2 border-b border-gray-200">
          <div className="h-1.5 w-1.5 rounded-full bg-black"></div>
          <h3 className="text-sm font-semibold text-gray-900">基本資訊</h3>
        </div>
        
        <div className="grid gap-4">
          <div className="grid gap-2">
            <Label htmlFor="title" className="text-sm font-medium text-gray-700">
              行程標題 <span className="text-red-500">*</span>
            </Label>
            <Input
              id="title"
              value={formData.title}
              onChange={(e) =>
                setFormData({ ...formData, title: e.target.value })
              }
              placeholder="例：東京賞櫻 5 日遊"
              className="rounded-full"
            />
          </div>
          
          <div className="grid grid-cols-2 gap-4">
            <div className="grid gap-2">
              <Label htmlFor="destinationCountry" className="text-sm font-medium text-gray-700">
                目的地國家 <span className="text-red-500">*</span>
              </Label>
              <Input
                id="destinationCountry"
                value={formData.destinationCountry}
                onChange={(e) =>
                  setFormData({ ...formData, destinationCountry: e.target.value })
                }
                placeholder="例：日本"
                className="rounded-full"
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="destinationCity" className="text-sm font-medium text-gray-700">
                目的地城市
              </Label>
              <Input
                id="destinationCity"
                value={formData.destinationCity}
                onChange={(e) =>
                  setFormData({ ...formData, destinationCity: e.target.value })
                }
                placeholder="例：東京"
                className="rounded-full"
              />
            </div>
          </div>

          <div className="grid gap-2">
            <Label htmlFor="destination" className="text-sm font-medium text-gray-700">
              目的地 (顯示用) <span className="text-red-500">*</span>
            </Label>
            <Input
              id="destination"
              value={formData.destination}
              onChange={(e) =>
                setFormData({ ...formData, destination: e.target.value })
              }
              placeholder="例：日本東京"
              className="rounded-full"
            />
          </div>
        </div>
      </div>

      {/* 行程詳情區塊 */}
      <div className="space-y-4">
        <div className="flex items-center gap-2 pb-2 border-b border-gray-200">
          <div className="h-1.5 w-1.5 rounded-full bg-black"></div>
          <h3 className="text-sm font-semibold text-gray-900">行程詳情</h3>
        </div>
        
        <div className="grid gap-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="grid gap-2">
              <Label htmlFor="duration" className="text-sm font-medium text-gray-700">
                天數
              </Label>
              <Input
                id="duration"
                type="number"
                min={1}
                value={formData.duration}
                onChange={(e) =>
                  setFormData({ ...formData, duration: parseInt(e.target.value) || 1 })
                }
                className="rounded-full"
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="price" className="text-sm font-medium text-gray-700">
                價格 (NT$)
              </Label>
              <Input
                id="price"
                type="number"
                min={0}
                value={formData.price}
                onChange={(e) =>
                  setFormData({ ...formData, price: parseInt(e.target.value) || 0 })
                }
                className="rounded-full"
              />
            </div>
          </div>

          <div className="grid gap-2">
            <Label htmlFor="description" className="text-sm font-medium text-gray-700">
              行程描述
            </Label>
            <Textarea
              id="description"
              value={formData.description}
              onChange={(e) =>
                setFormData({ ...formData, description: e.target.value })
              }
              placeholder="請輸入行程描述..."
              rows={3}
              className="rounded-2xl"
            />
          </div>

          <div className="grid gap-2">
            <Label htmlFor="imageUrl" className="text-sm font-medium text-gray-700">
              封面圖片網址
            </Label>
            <Input
              id="imageUrl"
              value={formData.imageUrl}
              onChange={(e) =>
                setFormData({ ...formData, imageUrl: e.target.value })
              }
              placeholder="https://..."
              className="rounded-full"
            />
          </div>
        </div>
      </div>

      {/* 分類與狀態區塊 */}
      <div className="space-y-4">
        <div className="flex items-center gap-2 pb-2 border-b border-gray-200">
          <div className="h-1.5 w-1.5 rounded-full bg-black"></div>
          <h3 className="text-sm font-semibold text-gray-900">分類與狀態</h3>
        </div>
        
        <div className="grid grid-cols-2 gap-4">
          <div className="grid gap-2">
            <Label htmlFor="category" className="text-sm font-medium text-gray-700">
              分類
            </Label>
            <Select
              value={formData.category}
              onValueChange={(v: any) => setFormData({ ...formData, category: v })}
            >
              <SelectTrigger className="rounded-full">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="group">團體旅遊</SelectItem>
                <SelectItem value="custom">客製旅遊</SelectItem>
                <SelectItem value="package">套裝行程</SelectItem>
                <SelectItem value="cruise">郵輪旅遊</SelectItem>
                <SelectItem value="theme">主題旅遊</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="status" className="text-sm font-medium text-gray-700">
              狀態
            </Label>
            <Select
              value={formData.status}
              onValueChange={(v: any) => setFormData({ ...formData, status: v })}
            >
              <SelectTrigger className="rounded-full">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="active">上架中</SelectItem>
                <SelectItem value="inactive">已下架</SelectItem>
                <SelectItem value="soldout">已售完</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
      </div>
    </div>
  );
}
