import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import DeparturesManagement from "./DeparturesManagement";
import { Calendar, Edit, Eye, EyeOff, ExternalLink, Loader2, Plus, Search, Sparkles, Star, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type TourFormData = {
  title: string;
  destination: string;
  destinationCountry: string;
  destinationCity: string;
  description: string;
  duration: number;
  price: number;
  imageUrl?: string;
  category: "group" | "custom" | "package" | "cruise" | "theme";
  status: "active" | "inactive" | "soldout";
  featured: number;
  maxParticipants?: number;
  highlights?: string;
  includes?: string;
  excludes?: string;
};

export default function ToursTab() {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [isBatchDeleteDialogOpen, setIsBatchDeleteDialogOpen] = useState(false);
  const [isAutoGenerateDialogOpen, setIsAutoGenerateDialogOpen] = useState(false);
  const [isPreviewDialogOpen, setIsPreviewDialogOpen] = useState(false);
  const [isDeparturesDialogOpen, setIsDeparturesDialogOpen] = useState(false);
  const [selectedTourForDepartures, setSelectedTourForDepartures] = useState<{id: number, title: string} | null>(null);
  const [autoGenerateUrl, setAutoGenerateUrl] = useState("");
  const [generatedTourData, setGeneratedTourData] = useState<any>(null);
  const [extractionStep, setExtractionStep] = useState<number>(0); // 0: 未開始, 1: 抓取網頁, 2: 解析內容, 3: AI 分析, 4: 儲存資料庫
  const [generationMode, setGenerationMode] = useState<"quick" | "complete">("quick"); // quick: 快速提取, complete: 完整生成
  const [selectedTourId, setSelectedTourId] = useState<number | null>(null);
  const [selectedTourIds, setSelectedTourIds] = useState<number[]>([]);
  const [statusFilter, setStatusFilter] = useState<"all" | "active" | "inactive">("all");
  const [featuredFilter, setFeaturedFilter] = useState<"all" | "featured" | "normal">("all");
  const [searchKeyword, setSearchKeyword] = useState<string>("");
  const [sortBy, setSortBy] = useState<"default" | "price-asc" | "price-desc" | "duration-asc" | "duration-desc" | "date-asc" | "date-desc">("default");
  const [formData, setFormData] = useState<TourFormData>({
    title: "",
    destination: "",
    destinationCountry: "",
    destinationCity: "",
    description: "",
    duration: 1,
    price: 0,
    imageUrl: "",
    category: "group",
    status: "active",
    featured: 0,
    maxParticipants: undefined,
    highlights: "",
    includes: "",
    excludes: "",
  });

  const utils = trpc.useUtils();
  const { data: tours, isLoading: toursLoading } = trpc.tours.list.useQuery();
  
  const createTourMutation = trpc.tours.create.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      setIsCreateDialogOpen(false);
      resetForm();
      toast.success("行程已成功建立");
    },
    onError: (error) => {
      toast.error(`建立失敗：${error.message}`);
    },
  });

  const updateTourMutation = trpc.tours.update.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      setIsEditDialogOpen(false);
      resetForm();
      toast.success("行程已成功更新");
    },
    onError: (error) => {
      toast.error(`更新失敗：${error.message}`);
    },
  });

  const deleteTourMutation = trpc.tours.delete.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      setIsDeleteDialogOpen(false);
      setSelectedTourId(null);
      toast.success("行程已成功刪除");
    },
    onError: (error) => {
      toast.error(`刪除失敗：${error.message}`);
    },
  });

  const batchDeleteToursMutation = trpc.tours.batchDelete.useMutation({
    onSuccess: (data) => {
      utils.tours.list.invalidate();
      setIsBatchDeleteDialogOpen(false);
      setSelectedTourIds([]);
      toast.success(`已成功刪除 ${data.deletedCount} 個行程`);
    },
    onError: (error) => {
      toast.error(`批量刪除失敗：${error.message}`);
    },
  });

  // 快速切換狀態 mutation
  const toggleStatusMutation = trpc.tours.update.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      toast.success("狀態已更新");
    },
    onError: (error) => {
      toast.error(`更新失敗：${error.message}`);
    },
  });

  // 快速切換熱門 mutation
  const toggleFeaturedMutation = trpc.tours.update.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      toast.success("熱門狀態已更新");
    },
    onError: (error) => {
      toast.error(`更新失敗：${error.message}`);
    },
  });

  // 完整生成 mutation (使用 MasterAgent)
  const autoGenerateCompleteMutation = trpc.tours.autoGenerateComplete.useMutation({
    onSuccess: (result) => {
      setExtractionStep(4); // 儲存資料庫完成
      if (result.success) {
        // 如果已自動儲存,直接刷新列表並顯示成功訊息
        if (result.tourId) {
          utils.tours.list.invalidate();
          setIsAutoGenerateDialogOpen(false);
          setAutoGenerateUrl("");
          setExtractionStep(0);
          toast.success(
            result.message || "行程已自動儲存!",
            {
              description: `行程 ID: ${result.tourId}`,
              duration: 5000,
            }
          );
        }
      }
    },
    onError: (error) => {
      setExtractionStep(0);
      console.error("[AutoGenerateComplete] Error:", error);
      toast.error(`完整生成失敗：${error.message}`, {
        description: "請檢查網址是否正確並重試",
        duration: 5000,
      });
    },
  });

  // 快速提取 mutation
  const autoGenerateMutation = trpc.tours.autoGenerate.useMutation({
    onSuccess: (result) => {
      setExtractionStep(4); // 儲存資料庫完成
      if (result.success) {
        // 如果已自動儲存，直接刷新列表並顯示成功訊息
        if (result.savedTour) {
          utils.tours.list.invalidate();
          setIsAutoGenerateDialogOpen(false);
          setAutoGenerateUrl("");
          setExtractionStep(0);
          toast.success(
            `行程已自動儲存！提取耗時 ${result.extractionTime?.toFixed(1) || '?'} 秒`,
            {
              description: `行程「${result.savedTour.title}」已新增到行程管理`,
              duration: 5000,
            }
          );
        } else if (result.data) {
          // 如果沒有自動儲存，顯示預覽對話框
          setGeneratedTourData(result.data);
          setIsAutoGenerateDialogOpen(false);
          setIsPreviewDialogOpen(true);
          setExtractionStep(0);
          toast.success("行程資訊提取成功！請檢視並確認");
        }
      }
    },
    onError: (error) => {
      setExtractionStep(0);
      console.error("[AutoGenerate] Error:", error);
      // 檢查是否是超時錯誤
      if (error.message?.includes("aborted") || error.message?.includes("timeout")) {
        toast.error("提取超時，請稍後再試", {
          description: "提取過程可能需要 30-60 秒，請稍候",
          duration: 5000,
        });
      } else if (error.message?.includes("JSON")) {
        toast.error("提取失敗：回應格式錯誤", {
          description: "請確認網址正確並重試",
          duration: 5000,
        });
      } else {
        toast.error(`自動生成失敗：${error.message}`);
      }
    },
  });

  const handleAutoGenerate = () => {
    if (!autoGenerateUrl.trim()) {
      toast.error("請輸入行程網址");
      return;
    }
    setExtractionStep(1); // 開始抓取網頁
    
    if (generationMode === "complete") {
      // 完整生成模式 - 使用 MasterAgent
      // 模擬進度更新 (完整生成需要更長時間)
      setTimeout(() => setExtractionStep(2), 5000); // 5秒後進入解析內容
      setTimeout(() => setExtractionStep(3), 10000); // 10秒後進入 AI 分析
      autoGenerateCompleteMutation.mutate({ url: autoGenerateUrl });
    } else {
      // 快速提取模式
      // 模擬進度更新
      setTimeout(() => setExtractionStep(2), 3000); // 3秒後進入解析內容
      setTimeout(() => setExtractionStep(3), 6000); // 6秒後進入 AI 分析
      autoGenerateMutation.mutate({ url: autoGenerateUrl });
    }
  };

  const handleConfirmGeneratedTour = () => {
    if (generatedTourData) {
      // Prepare data for creation
      const tourData = {
        title: generatedTourData.title,
        destination: generatedTourData.destination,
        destinationCountry: generatedTourData.destinationCountry || "未指定",
        destinationCity: generatedTourData.destinationCity || "未指定",
        description: generatedTourData.description,
        duration: generatedTourData.duration,
        price: generatedTourData.price,
        imageUrl: generatedTourData.imageUrl,
        category: "group" as const,
        status: "inactive" as const, // 預設為下架，讓管理員確認後再上架
        featured: 0,
        highlights: generatedTourData.highlights,
        includes: generatedTourData.includes,
        excludes: generatedTourData.excludes,
        // New enhanced fields
        productCode: generatedTourData.productCode,
        promotionText: generatedTourData.promotionText,
        tags: generatedTourData.tags,
        departureCountry: generatedTourData.departureCountry,
        departureCity: generatedTourData.departureCity,
        departureAirportCode: generatedTourData.departureAirportCode,
        departureAirportName: generatedTourData.departureAirportName,
        destinationRegion: generatedTourData.destinationRegion,
        destinationAirportCode: generatedTourData.destinationAirportCode,
        destinationAirportName: generatedTourData.destinationAirportName,
        destinationDescription: generatedTourData.destinationDescription,
        nights: generatedTourData.nights,
        priceUnit: generatedTourData.priceUnit,
        availableSeats: generatedTourData.availableSeats,
        outboundAirline: generatedTourData.outboundAirline,
        outboundFlightNo: generatedTourData.outboundFlightNo,
        outboundDepartureTime: generatedTourData.outboundDepartureTime,
        outboundArrivalTime: generatedTourData.outboundArrivalTime,
        outboundFlightDuration: generatedTourData.outboundFlightDuration,
        inboundAirline: generatedTourData.inboundAirline,
        inboundFlightNo: generatedTourData.inboundFlightNo,
        inboundDepartureTime: generatedTourData.inboundDepartureTime,
        inboundArrivalTime: generatedTourData.inboundArrivalTime,
        inboundFlightDuration: generatedTourData.inboundFlightDuration,
        hotelName: generatedTourData.hotelName,
        hotelGrade: generatedTourData.hotelGrade,
        hotelNights: generatedTourData.hotelNights,
        hotelLocation: generatedTourData.hotelLocation,
        hotelDescription: generatedTourData.hotelDescription,
        hotelFacilities: generatedTourData.hotelFacilities,
        hotelRoomType: generatedTourData.hotelRoomType,
        hotelRoomSize: generatedTourData.hotelRoomSize,
        hotelCheckIn: generatedTourData.hotelCheckIn,
        hotelCheckOut: generatedTourData.hotelCheckOut,
        hotelSpecialOffers: generatedTourData.hotelSpecialOffers,
        hotelWebsite: generatedTourData.hotelWebsite,
        attractions: generatedTourData.attractions,
        dailyItinerary: generatedTourData.dailyItinerary,
        optionalTours: generatedTourData.optionalTours,
        specialReminders: generatedTourData.specialReminders,
        notes: generatedTourData.notes,
        safetyGuidelines: generatedTourData.safetyGuidelines,
        flightRules: generatedTourData.flightRules,
        sourceUrl: generatedTourData.sourceUrl,
        isAutoGenerated: 1,
        airline: generatedTourData.airline,
      };

      createTourMutation.mutate(tourData);
      setIsPreviewDialogOpen(false);
      setGeneratedTourData(null);
      setAutoGenerateUrl("");
    }
  };

  const resetForm = () => {
    setFormData({
      title: "",
      destination: "",
      destinationCountry: "",
      destinationCity: "",
      description: "",
      duration: 1,
      price: 0,
      imageUrl: "",
      category: "group",
      status: "active",
      featured: 0,
      maxParticipants: undefined,
      highlights: "",
      includes: "",
      excludes: "",
    });
  };

  const handleCreate = () => {
    createTourMutation.mutate(formData);
  };

  const handleEdit = (tourId: number) => {
    const tour = tours?.find((t) => t.id === tourId);
    if (tour) {
      setFormData({
        title: tour.title,
        destination: tour.destination,
        destinationCountry: tour.destinationCountry || "",
        destinationCity: tour.destinationCity || "",
        description: tour.description,
        duration: tour.duration,
        price: tour.price,
        imageUrl: tour.imageUrl || "",
        category: tour.category,
        status: tour.status,
        featured: tour.featured,
        maxParticipants: tour.maxParticipants || undefined,
        highlights: tour.highlights || "",
        includes: tour.includes || "",
        excludes: tour.excludes || "",
      });
      setSelectedTourId(tourId);
      setIsEditDialogOpen(true);
    }
  };

  const handleUpdate = () => {
    if (selectedTourId) {
      updateTourMutation.mutate({
        id: selectedTourId,
        ...formData,
      });
    }
  };

  const handleDelete = (tourId: number) => {
    setSelectedTourId(tourId);
    setIsDeleteDialogOpen(true);
  };

  const confirmDelete = () => {
    if (selectedTourId) {
      deleteTourMutation.mutate({ id: selectedTourId });
    }
  };

  const handleSelectTour = (tourId: number, checked: boolean) => {
    if (checked) {
      setSelectedTourIds([...selectedTourIds, tourId]);
    } else {
      setSelectedTourIds(selectedTourIds.filter((id) => id !== tourId));
    }
  };

  const handleSelectAll = (checked: boolean) => {
    if (checked && filteredTours.length > 0) {
      setSelectedTourIds(filteredTours.map((tour) => tour.id));
    } else {
      setSelectedTourIds([]);
    }
  };

  const handleBatchDelete = () => {
    if (selectedTourIds.length > 0) {
      setIsBatchDeleteDialogOpen(true);
    }
  };

  const confirmBatchDelete = () => {
    if (selectedTourIds.length > 0) {
      batchDeleteToursMutation.mutate({ ids: selectedTourIds });
    }
  };

  // 篩選、搜尋和排序後的行程列表
  const filteredAndSortedTours = (() => {
    // 第一步：篩選
    let result = tours?.filter((tour) => {
      // 上架狀態篩選
      if (statusFilter === "active" && tour.status !== "active") return false;
      if (statusFilter === "inactive" && tour.status !== "inactive") return false;
      // 熱門狀態篩選
      if (featuredFilter === "featured" && tour.featured !== 1) return false;
      if (featuredFilter === "normal" && tour.featured !== 0) return false;
      // 關鍵字搜尋（行程名稱或目的地）
      if (searchKeyword.trim()) {
        const keyword = searchKeyword.toLowerCase();
        const matchTitle = tour.title.toLowerCase().includes(keyword);
        const matchDestination = tour.destination.toLowerCase().includes(keyword);
        if (!matchTitle && !matchDestination) return false;
      }
      return true;
    }) || [];

    // 第二步：排序
    if (sortBy !== "default") {
      result = [...result].sort((a, b) => {
        switch (sortBy) {
          case "price-asc":
            return a.price - b.price;
          case "price-desc":
            return b.price - a.price;
          case "duration-asc":
            return a.duration - b.duration;
          case "duration-desc":
            return b.duration - a.duration;
          case "date-asc":
            return new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime();
          case "date-desc":
            return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
          default:
            return 0;
        }
      });
    }

    return result;
  })();

  // 為了相容性，保留 filteredTours 別名
  const filteredTours = filteredAndSortedTours;

  const isAllSelected = filteredTours.length > 0 && selectedTourIds.length === filteredTours.length;
  const isSomeSelected = selectedTourIds.length > 0 && selectedTourIds.length < filteredTours.length;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">行程管理</h2>
        </div>
        <div className="flex items-center gap-3">
          {selectedTourIds.length > 0 && (
            <Button
              onClick={handleBatchDelete}
              variant="outline"
              className="border-red-300 text-red-600 hover:bg-red-50 rounded-full"
            >
              <Trash2 className="h-4 w-4 mr-2" />
              刪除已選 ({selectedTourIds.length})
            </Button>
          )}
          <Button
            onClick={() => {
              setAutoGenerateUrl("");
              setIsAutoGenerateDialogOpen(true);
            }}
            variant="outline"
            className="border-purple-300 text-purple-600 hover:bg-purple-50 rounded-full"
          >
            <Sparkles className="h-4 w-4 mr-2" />
            AI 自動生成
          </Button>
          <Button
            onClick={() => {
              resetForm();
              setIsCreateDialogOpen(true);
            }}
            className="bg-black text-white hover:bg-gray-800 rounded-full"
          >
            <Plus className="h-4 w-4 mr-2" />
            新增行程
          </Button>
        </div>
      </div>

      {/* 簡潔篩選區塊 */}
      <div className="flex flex-col gap-4">
        {/* 搜尋和排序 */}
        <div className="flex items-center gap-4">
          <div className="relative flex-1 max-w-md">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
            <Input
              type="text"
              placeholder="搜尋行程..."
              value={searchKeyword}
              onChange={(e) => setSearchKeyword(e.target.value)}
              className="pl-10 h-10 bg-white border-gray-200"
            />
          </div>
          <Select value={sortBy} onValueChange={(value: typeof sortBy) => setSortBy(value)}>
            <SelectTrigger className="w-36 h-10 bg-white border-gray-200">
              <SelectValue placeholder="排序" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="default">預設</SelectItem>
              <SelectItem value="price-asc">價格低→高</SelectItem>
              <SelectItem value="price-desc">價格高→低</SelectItem>
              <SelectItem value="duration-asc">天數短→長</SelectItem>
              <SelectItem value="duration-desc">天數長→短</SelectItem>
              <SelectItem value="date-desc">最新</SelectItem>
              <SelectItem value="date-asc">最舊</SelectItem>
            </SelectContent>
          </Select>
          <Select value={statusFilter} onValueChange={(value: "all" | "active" | "inactive") => setStatusFilter(value)}>
            <SelectTrigger className="w-28 h-10 bg-white border-gray-200">
              <SelectValue placeholder="狀態" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">全部</SelectItem>
              <SelectItem value="active">已上架</SelectItem>
              <SelectItem value="inactive">未上架</SelectItem>
            </SelectContent>
          </Select>
          <Select value={featuredFilter} onValueChange={(value: "all" | "featured" | "normal") => setFeaturedFilter(value)}>
            <SelectTrigger className="w-28 h-10 bg-white border-gray-200">
              <SelectValue placeholder="熱門" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">全部</SelectItem>
              <SelectItem value="featured">熱門</SelectItem>
              <SelectItem value="normal">普通</SelectItem>
            </SelectContent>
          </Select>
          {(statusFilter !== "all" || featuredFilter !== "all" || searchKeyword.trim() || sortBy !== "default") && (
            <button
              onClick={() => {
                setStatusFilter("all");
                setFeaturedFilter("all");
                setSearchKeyword("");
                setSortBy("default");
              }}
              className="text-sm text-gray-500 hover:text-gray-700"
            >
              清除
            </button>
          )}
          <span className="ml-auto text-sm text-gray-500">
            共 {filteredTours.length} 筆
          </span>
        </div>
      </div>

      {/* Tours Table */}
      <div className="bg-white rounded-3xl border-2 border-gray-200 overflow-hidden">
        {toursLoading ? (
          <div className="p-8 text-center">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-black mx-auto mb-2"></div>
            <p className="text-gray-600">載入中...</p>
          </div>
        ) : filteredTours.length > 0 ? (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50 border-b-2 border-gray-200">
                <tr>
                  <th className="px-6 py-4 text-left w-12">
                    <Checkbox
                      checked={isAllSelected}
                      onCheckedChange={handleSelectAll}
                      className="data-[state=indeterminate]:bg-gray-400"
                      data-state={isSomeSelected ? "indeterminate" : isAllSelected ? "checked" : "unchecked"}
                    />
                  </th>
                  <th className="px-6 py-4 text-left text-sm font-semibold text-gray-700">
                    ID
                  </th>
                  <th className="px-6 py-4 text-left text-sm font-semibold text-gray-700 min-w-[200px]">
                    標題
                  </th>
                  <th className="px-6 py-4 text-left text-sm font-semibold text-gray-700">
                    目的地
                  </th>
                  <th className="px-6 py-4 text-center text-sm font-semibold text-gray-700">
                    天數
                  </th>
                  <th className="px-6 py-4 text-right text-sm font-semibold text-gray-700">
                    價格
                  </th>
                  <th className="px-6 py-4 text-left text-sm font-semibold text-gray-700">
                    分類
                  </th>
                  <th className="px-6 py-4 text-center text-sm font-semibold text-gray-700">
                    狀態
                  </th>
                  {isAdmin && (
                    <>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-gray-700 min-w-[150px]">
                        來源 URL
                      </th>
                      <th className="px-6 py-4 text-center text-sm font-semibold text-gray-700">
                        原創性評分
                      </th>
                    </>
                  )}
                  <th className="px-6 py-4 text-right text-sm font-semibold text-gray-700 min-w-[280px]">
                    操作
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {filteredTours.map((tour) => (
                  <tr key={tour.id} className={`hover:bg-gray-50 transition-colors ${selectedTourIds.includes(tour.id) ? 'bg-blue-50' : ''}`}>
                    <td className="px-6 py-5">
                      <Checkbox
                        checked={selectedTourIds.includes(tour.id)}
                        onCheckedChange={(checked) => handleSelectTour(tour.id, checked as boolean)}
                      />
                    </td>
                    <td className="px-6 py-5 whitespace-nowrap text-sm text-gray-600 font-mono">
                      {tour.id}
                    </td>
                    <td className="px-6 py-5 text-sm text-gray-900 font-medium">{tour.title}</td>
                    <td className="px-6 py-5 whitespace-nowrap text-sm text-gray-700">
                      {tour.destination}
                    </td>
                    <td className="px-6 py-5 whitespace-nowrap text-sm text-gray-700 text-center">
                      {tour.duration} 天
                    </td>
                    <td className="px-6 py-5 whitespace-nowrap text-sm text-gray-900 font-semibold text-right">
                      NT$ {tour.price.toLocaleString()}
                    </td>
                    <td className="px-6 py-5 whitespace-nowrap text-sm text-gray-700">
                      {getCategoryLabel(tour.category)}
                    </td>
                    <td className="px-6 py-5 whitespace-nowrap text-center">
                      <span
                        className={`inline-flex px-3 py-1.5 text-xs font-semibold rounded-full ${
                          tour.status === "active"
                            ? "bg-green-100 text-green-800"
                            : tour.status === "soldout"
                              ? "bg-red-100 text-red-800"
                              : "bg-gray-100 text-gray-800"
                        }`}
                      >
                        {getStatusLabel(tour.status)}
                      </span>
                    </td>
                    {isAdmin && (
                      <>
                        <td className="px-6 py-5 text-sm text-gray-700">
                          {tour.sourceUrl ? (
                            <a
                              href={tour.sourceUrl}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="flex items-center gap-1 text-blue-600 hover:text-blue-800 hover:underline"
                              title="查看來源網頁"
                            >
                              <ExternalLink className="h-3.5 w-3.5" />
                              <span className="truncate max-w-[120px]">
                                {new URL(tour.sourceUrl).hostname}
                              </span>
                            </a>
                          ) : (
                            <span className="text-gray-400">無</span>
                          )}
                        </td>
                        <td className="px-6 py-5 whitespace-nowrap text-center">
                          {tour.originalityScore ? (
                            <span
                              className={`inline-flex px-3 py-1.5 text-xs font-semibold rounded-full ${
                                Number(tour.originalityScore) >= 90
                                  ? "bg-green-100 text-green-800"
                                  : Number(tour.originalityScore) >= 70
                                    ? "bg-yellow-100 text-yellow-800"
                                    : Number(tour.originalityScore) >= 60
                                      ? "bg-orange-100 text-orange-800"
                                      : "bg-red-100 text-red-800"
                              }`}
                            >
                              {Number(tour.originalityScore).toFixed(1)}
                            </span>
                          ) : (
                            <span className="text-gray-400">無</span>
                          )}
                        </td>
                      </>
                    )}
                    <td className="px-6 py-5 whitespace-nowrap text-right">
                      <div className="flex items-center justify-end gap-1">
                        {/* 快速切換上架/下架 */}
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => {
                            toggleStatusMutation.mutate({
                              id: tour.id,
                              status: tour.status === "active" ? "inactive" : "active",
                            });
                          }}
                          className={`h-9 w-9 p-0 rounded-full transition-colors ${tour.status === "active" ? "text-green-600 hover:bg-green-50 hover:text-green-700" : "text-gray-400 hover:bg-gray-100 hover:text-gray-600"}`}
                          title={tour.status === "active" ? "點擊下架" : "點擊上架"}
                          disabled={toggleStatusMutation.isPending}
                        >
                          {tour.status === "active" ? <Eye className="h-4 w-4" /> : <EyeOff className="h-4 w-4" />}
                        </Button>
                        {/* 快速切換熱門 */}
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => {
                            toggleFeaturedMutation.mutate({
                              id: tour.id,
                              featured: tour.featured === 1 ? 0 : 1,
                            });
                          }}
                          className={`h-9 w-9 p-0 rounded-full transition-colors ${tour.featured === 1 ? "text-yellow-500 hover:bg-yellow-50 hover:text-yellow-600" : "text-gray-400 hover:bg-gray-100 hover:text-gray-600"}`}
                          title={tour.featured === 1 ? "取消熱門" : "設為熱門"}
                          disabled={toggleFeaturedMutation.isPending}
                        >
                          <Star className={`h-4 w-4 ${tour.featured === 1 ? "fill-current" : ""}`} />
                        </Button>
                        <div className="w-px h-6 bg-gray-200 mx-1"></div>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => {
                            setSelectedTourForDepartures({id: tour.id, title: tour.title});
                            setIsDeparturesDialogOpen(true);
                          }}
                          className="h-9 w-9 p-0 rounded-full hover:bg-gray-100 transition-colors"
                          title="管理出發日期"
                        >
                          <Calendar className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleEdit(tour.id)}
                          className="h-9 w-9 p-0 rounded-full hover:bg-blue-50 hover:text-blue-600 transition-colors"
                          title="編輯行程"
                        >
                          <Edit className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleDelete(tour.id)}
                          className="h-9 w-9 p-0 rounded-full text-red-600 hover:bg-red-50 hover:text-red-700 transition-colors"
                          title="刪除行程"
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : tours && tours.length > 0 ? (
          <div className="p-8 text-center">
            <p className="text-gray-600">沒有符合篩選條件的行程</p>
            <Button
              variant="link"
              onClick={() => {
                setStatusFilter("all");
                setFeaturedFilter("all");
              }}
              className="text-primary mt-2"
            >
              清除篩選條件
            </Button>
          </div>
        ) : (
          <div className="p-8 text-center">
            <p className="text-gray-600">尚無行程資料</p>
          </div>
        )}
      </div>

      {/* Create Dialog */}
      <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto rounded-3xl">
          <DialogHeader>
            <DialogTitle>新增行程</DialogTitle>
            <DialogDescription>填寫以下資訊以建立新的旅遊行程</DialogDescription>
          </DialogHeader>
          <TourForm formData={formData} setFormData={setFormData} />
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsCreateDialogOpen(false)}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              onClick={handleCreate}
              disabled={createTourMutation.isPending}
              className="bg-black text-white hover:bg-gray-800 rounded-full"
            >
              {createTourMutation.isPending ? "建立中..." : "建立"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Edit Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto rounded-3xl">
          <DialogHeader>
            <DialogTitle>編輯行程</DialogTitle>
            <DialogDescription>修改行程資訊</DialogDescription>
          </DialogHeader>
          <TourForm formData={formData} setFormData={setFormData} />
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsEditDialogOpen(false)}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              onClick={handleUpdate}
              disabled={updateTourMutation.isPending}
              className="bg-black text-white hover:bg-gray-800 rounded-full"
            >
              {updateTourMutation.isPending ? "更新中..." : "更新"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <DialogContent className="rounded-3xl">
          <DialogHeader>
            <DialogTitle>確認刪除</DialogTitle>
            <DialogDescription>
              您確定要刪除這個行程嗎？此操作無法復原。
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsDeleteDialogOpen(false)}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              onClick={confirmDelete}
              disabled={deleteTourMutation.isPending}
              className="bg-red-600 text-white hover:bg-red-700 rounded-full"
            >
              {deleteTourMutation.isPending ? "刪除中..." : "刪除"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Batch Delete Confirmation Dialog */}
      <Dialog open={isBatchDeleteDialogOpen} onOpenChange={setIsBatchDeleteDialogOpen}>
        <DialogContent className="rounded-3xl">
          <DialogHeader>
            <DialogTitle>確認批量刪除</DialogTitle>
            <DialogDescription>
              您確定要刪除選取的 {selectedTourIds.length} 個行程嗎？此操作無法復原。
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsBatchDeleteDialogOpen(false)}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              onClick={confirmBatchDelete}
              disabled={batchDeleteToursMutation.isPending}
              className="bg-red-600 text-white hover:bg-red-700 rounded-full"
            >
              {batchDeleteToursMutation.isPending ? "刪除中..." : `刪除 ${selectedTourIds.length} 個行程`}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Departures Management Dialog */}
      <Dialog open={isDeparturesDialogOpen} onOpenChange={setIsDeparturesDialogOpen}>
        <DialogContent className="max-w-6xl max-h-[90vh] overflow-y-auto rounded-3xl">
          <DialogHeader>
            <DialogTitle>出發日期管理</DialogTitle>
            <DialogDescription>
              管理此行程的所有出發日期與價格
            </DialogDescription>
          </DialogHeader>
          {selectedTourForDepartures && (
            <DeparturesManagement
              tourId={selectedTourForDepartures.id}
              tourTitle={selectedTourForDepartures.title}
            />
          )}
        </DialogContent>
      </Dialog>

      {/* Auto Generate Dialog */}
      <Dialog open={isAutoGenerateDialogOpen} onOpenChange={setIsAutoGenerateDialogOpen}>
        <DialogContent className="max-w-lg rounded-3xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-purple-600" />
              AI 自動生成行程
            </DialogTitle>
            <DialogDescription>
              輸入旅遊行程網址，系統將自動提取行程資訊並生成統一格式的行程
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            {/* 生成模式選擇 */}
            <div className="grid gap-3">
              <Label>生成模式</Label>
              <div className="grid grid-cols-2 gap-3">
                <button
                  type="button"
                  onClick={() => setGenerationMode("quick")}
                  disabled={autoGenerateMutation.isPending || autoGenerateCompleteMutation.isPending}
                  className={`p-4 rounded-2xl border-2 transition-all text-left ${
                    generationMode === "quick"
                      ? "border-purple-600 bg-purple-50"
                      : "border-gray-200 hover:border-purple-300"
                  }`}
                >
                  <div className="flex items-start gap-3">
                    <div className={`mt-0.5 h-5 w-5 rounded-full border-2 flex items-center justify-center ${
                      generationMode === "quick" ? "border-purple-600" : "border-gray-300"
                    }`}>
                      {generationMode === "quick" && (
                        <div className="h-2.5 w-2.5 rounded-full bg-purple-600" />
                      )}
                    </div>
                    <div className="flex-1">
                      <div className="font-semibold text-sm mb-1">快速提取</div>
                      <div className="text-xs text-gray-600">
                        約 15 秒 · 提取基本資訊
                      </div>
                    </div>
                  </div>
                </button>
                <button
                  type="button"
                  onClick={() => setGenerationMode("complete")}
                  disabled={autoGenerateMutation.isPending || autoGenerateCompleteMutation.isPending}
                  className={`p-4 rounded-2xl border-2 transition-all text-left ${
                    generationMode === "complete"
                      ? "border-purple-600 bg-purple-50"
                      : "border-gray-200 hover:border-purple-300"
                  }`}
                >
                  <div className="flex items-start gap-3">
                    <div className={`mt-0.5 h-5 w-5 rounded-full border-2 flex items-center justify-center ${
                      generationMode === "complete" ? "border-purple-600" : "border-gray-300"
                    }`}>
                      {generationMode === "complete" && (
                        <div className="h-2.5 w-2.5 rounded-full bg-purple-600" />
                      )}
                    </div>
                    <div className="flex-1">
                      <div className="font-semibold text-sm mb-1 flex items-center gap-1">
                        完整生成
                        <Sparkles className="h-3 w-3 text-purple-600" />
                      </div>
                      <div className="text-xs text-gray-600">
                        約 60-90 秒 · Hero 圖片 + 配色主題 + 豐富內容
                      </div>
                    </div>
                  </div>
                </button>
              </div>
              {generationMode === "complete" && (
                <div className="bg-purple-50 border border-purple-200 rounded-xl p-3">
                  <p className="text-xs text-purple-900 font-medium mb-1">✨ 完整生成包含:</p>
                  <ul className="text-xs text-purple-800 space-y-0.5 ml-4">
                    <li>• AI 生成的 Hero 圖片</li>
                    <li>• 根據目的地自動配色</li>
                    <li>• 詩意化的行程描述</li>
                    <li>• Unsplash 真實景點圖片</li>
                    <li>• 完整的費用說明與注意事項</li>
                  </ul>
                </div>
              )}
            </div>
            
            <div className="grid gap-2">
              <Label htmlFor="autoGenerateUrl">行程網址</Label>
              <Input
                id="autoGenerateUrl"
                value={autoGenerateUrl}
                onChange={(e) => setAutoGenerateUrl(e.target.value)}
                placeholder="https://travel.example.com/tour/..."
                className="rounded-full"
                disabled={autoGenerateMutation.isPending || autoGenerateCompleteMutation.isPending}
              />
            </div>
            <p className="text-sm text-gray-500">
              支援雄獅旅遊、可樂旅遊、雄鸟旅遊等主流旅遊網站的行程頁面
            </p>
            
            {/* 進度指示器 */}
            {(autoGenerateMutation.isPending || autoGenerateCompleteMutation.isPending) && (
              <div className="bg-gray-50 rounded-2xl p-4 space-y-3">
                <p className="text-sm font-medium text-gray-700">提取進度</p>
                <div className="space-y-2">
                  <div className={`flex items-center gap-3 ${extractionStep >= 1 ? 'text-purple-600' : 'text-gray-400'}`}>
                    {extractionStep === 1 ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : extractionStep > 1 ? (
                      <div className="h-4 w-4 rounded-full bg-purple-600 flex items-center justify-center">
                        <span className="text-white text-xs">✓</span>
                      </div>
                    ) : (
                      <div className="h-4 w-4 rounded-full border-2 border-gray-300" />
                    )}
                    <span className="text-sm">步驟 1: 抓取網頁內容</span>
                  </div>
                  <div className={`flex items-center gap-3 ${extractionStep >= 2 ? 'text-purple-600' : 'text-gray-400'}`}>
                    {extractionStep === 2 ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : extractionStep > 2 ? (
                      <div className="h-4 w-4 rounded-full bg-purple-600 flex items-center justify-center">
                        <span className="text-white text-xs">✓</span>
                      </div>
                    ) : (
                      <div className="h-4 w-4 rounded-full border-2 border-gray-300" />
                    )}
                    <span className="text-sm">步驟 2: 解析行程資訊</span>
                  </div>
                  <div className={`flex items-center gap-3 ${extractionStep >= 3 ? 'text-purple-600' : 'text-gray-400'}`}>
                    {extractionStep === 3 ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : extractionStep > 3 ? (
                      <div className="h-4 w-4 rounded-full bg-purple-600 flex items-center justify-center">
                        <span className="text-white text-xs">✓</span>
                      </div>
                    ) : (
                      <div className="h-4 w-4 rounded-full border-2 border-gray-300" />
                    )}
                    <span className="text-sm">步驟 3: AI 智能分析與整理</span>
                  </div>
                  <div className={`flex items-center gap-3 ${extractionStep >= 4 ? 'text-purple-600' : 'text-gray-400'}`}>
                    {extractionStep === 4 ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : extractionStep > 4 ? (
                      <div className="h-4 w-4 rounded-full bg-purple-600 flex items-center justify-center">
                        <span className="text-white text-xs">✓</span>
                      </div>
                    ) : (
                      <div className="h-4 w-4 rounded-full border-2 border-gray-300" />
                    )}
                    <span className="text-sm">步驟 4: 儲存至資料庫</span>
                  </div>
                </div>
                <p className="text-xs text-gray-500 mt-2">
                  {generationMode === "complete" 
                    ? "完整生成過程約需 60-90 秒，請耐心等候..." 
                    : "提取過程約需 15-30 秒，請耐心等候..."}
                </p>
              </div>
            )}
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsAutoGenerateDialogOpen(false)}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              onClick={handleAutoGenerate}
              disabled={autoGenerateMutation.isPending || autoGenerateCompleteMutation.isPending}
              className="bg-purple-600 text-white hover:bg-purple-700 rounded-full"
            >
              {(autoGenerateMutation.isPending || autoGenerateCompleteMutation.isPending) ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  {generationMode === "complete" ? "生成中..." : "提取中..."}
                </>
              ) : (
                <>
                  <Sparkles className="h-4 w-4 mr-2" />
                  {generationMode === "complete" ? "開始完整生成" : "開始快速提取"}
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Preview Generated Tour Dialog */}
      <Dialog open={isPreviewDialogOpen} onOpenChange={setIsPreviewDialogOpen}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto rounded-3xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-purple-600" />
              行程資訊預覽
            </DialogTitle>
            <DialogDescription>
              請檢查自動提取的行程資訊，確認無誤後即可儲存
            </DialogDescription>
          </DialogHeader>
          {generatedTourData && (
            <div className="grid gap-6 py-4">
              {/* Basic Info */}
              <div className="bg-purple-50 rounded-2xl p-4">
                <h3 className="font-semibold text-purple-900 mb-3">基本資訊</h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-gray-500">標題：</span>
                    <span className="ml-2 font-medium">{generatedTourData.title}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">產品代碼：</span>
                    <span className="ml-2">{generatedTourData.productCode || '-'}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">促銷文字：</span>
                    <span className="ml-2 text-red-600">{generatedTourData.promotionText || '-'}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">天數：</span>
                    <span className="ml-2">{generatedTourData.duration} 天 {generatedTourData.nights || (generatedTourData.duration - 1)} 晚</span>
                  </div>
                  <div>
                    <span className="text-gray-500">價格：</span>
                    <span className="ml-2 font-bold text-lg text-green-600">NT$ {generatedTourData.price?.toLocaleString()}</span>
                  </div>
                </div>
              </div>

              {/* Location Info */}
              <div className="bg-blue-50 rounded-2xl p-4">
                <h3 className="font-semibold text-blue-900 mb-3">地點資訊</h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-gray-500">出發國家/城市：</span>
                    <span className="ml-2">{generatedTourData.departureCountry} / {generatedTourData.departureCity}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">出發機場：</span>
                    <span className="ml-2">{generatedTourData.departureAirportCode} {generatedTourData.departureAirportName}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">目的地國家/城市：</span>
                    <span className="ml-2 font-medium">{generatedTourData.destinationCountry} / {generatedTourData.destinationCity}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">目的地機場：</span>
                    <span className="ml-2">{generatedTourData.destinationAirportCode} {generatedTourData.destinationAirportName}</span>
                  </div>
                </div>
              </div>

              {/* Flight Info */}
              <div className="bg-orange-50 rounded-2xl p-4">
                <h3 className="font-semibold text-orange-900 mb-3">航班資訊</h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div className="border-r border-orange-200 pr-4">
                    <p className="font-medium mb-2">去程</p>
                    <p><span className="text-gray-500">航空公司：</span>{generatedTourData.outboundAirline || '-'}</p>
                    <p><span className="text-gray-500">時間：</span>{generatedTourData.outboundDepartureTime} → {generatedTourData.outboundArrivalTime}</p>
                    <p><span className="text-gray-500">飛行時間：</span>{generatedTourData.outboundFlightDuration || '-'}</p>
                  </div>
                  <div className="pl-4">
                    <p className="font-medium mb-2">回程</p>
                    <p><span className="text-gray-500">航空公司：</span>{generatedTourData.inboundAirline || '-'}</p>
                    <p><span className="text-gray-500">時間：</span>{generatedTourData.inboundDepartureTime} → {generatedTourData.inboundArrivalTime}</p>
                    <p><span className="text-gray-500">飛行時間：</span>{generatedTourData.inboundFlightDuration || '-'}</p>
                  </div>
                </div>
              </div>

              {/* Hotel Info */}
              <div className="bg-green-50 rounded-2xl p-4">
                <h3 className="font-semibold text-green-900 mb-3">住宿資訊</h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-gray-500">酒店名稱：</span>
                    <span className="ml-2 font-medium">{generatedTourData.hotelName || '-'}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">酒店等級：</span>
                    <span className="ml-2">{generatedTourData.hotelGrade || '-'}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">位置：</span>
                    <span className="ml-2">{generatedTourData.hotelLocation || '-'}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">入住/退房：</span>
                    <span className="ml-2">{generatedTourData.hotelCheckIn || '-'} / {generatedTourData.hotelCheckOut || '-'}</span>
                  </div>
                </div>
              </div>

              {/* Description */}
              <div className="bg-gray-50 rounded-2xl p-4">
                <h3 className="font-semibold text-gray-900 mb-3">行程描述</h3>
                <p className="text-sm text-gray-700 whitespace-pre-wrap">{generatedTourData.description}</p>
              </div>

              {/* Source URL */}
              <div className="text-xs text-gray-400">
                來源：<a href={generatedTourData.sourceUrl} target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">{generatedTourData.sourceUrl}</a>
              </div>
            </div>
          )}
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setIsPreviewDialogOpen(false);
                setGeneratedTourData(null);
              }}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              onClick={handleConfirmGeneratedTour}
              disabled={createTourMutation.isPending}
              className="bg-purple-600 text-white hover:bg-purple-700 rounded-full"
            >
              {createTourMutation.isPending ? "儲存中..." : "確認儲存"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// Tour Form Component
function TourForm({
  formData,
  setFormData,
}: {
  formData: TourFormData;
  setFormData: React.Dispatch<React.SetStateAction<TourFormData>>;
}) {
  return (
    <div className="grid gap-6 py-4">
      {/* 基本資訊區塊 */}
      <div className="space-y-4">
        <div className="flex items-center gap-2 pb-2 border-b border-gray-200">
          <div className="h-1.5 w-1.5 rounded-full bg-black"></div>
          <h3 className="text-sm font-semibold text-gray-900">基本資訊</h3>
        </div>
        
        <div className="grid gap-4">
          <div className="grid gap-2">
            <Label htmlFor="title" className="text-sm font-medium text-gray-700">
              行程標題 <span className="text-red-500">*</span>
            </Label>
            <Input
              id="title"
              value={formData.title}
              onChange={(e) =>
                setFormData({ ...formData, title: e.target.value })
              }
              placeholder="例：東京賞櫻 5 日遊"
              className="rounded-full"
            />
          </div>

          <div className="grid grid-cols-3 gap-4">
            <div className="grid gap-2">
              <Label htmlFor="destination" className="text-sm font-medium text-gray-700">
                目的地 <span className="text-red-500">*</span>
              </Label>
              <Input
                id="destination"
                value={formData.destination}
                onChange={(e) =>
                  setFormData({ ...formData, destination: e.target.value })
                }
                placeholder="例：日本東京"
                className="rounded-full"
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="duration" className="text-sm font-medium text-gray-700">
                天數 <span className="text-red-500">*</span>
              </Label>
              <Input
                id="duration"
                type="number"
                min={1}
                value={formData.duration}
                onChange={(e) =>
                  setFormData({ ...formData, duration: parseInt(e.target.value) || 1 })
                }
                placeholder="5"
                className="rounded-full"
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="maxParticipants" className="text-sm font-medium text-gray-700">
                人數上限
              </Label>
              <Input
                id="maxParticipants"
                type="number"
                min={1}
                value={formData.maxParticipants || ""}
                onChange={(e) =>
                  setFormData({
                    ...formData,
                    maxParticipants: e.target.value ? parseInt(e.target.value) : undefined,
                  })
                }
                placeholder="不限"
                className="rounded-full"
              />
            </div>
          </div>

          <div className="grid grid-cols-3 gap-4">
            <div className="grid gap-2">
              <Label htmlFor="price" className="text-sm font-medium text-gray-700">
                價格 (NT$) <span className="text-red-500">*</span>
              </Label>
              <Input
                id="price"
                type="number"
                min={0}
                value={formData.price}
                onChange={(e) =>
                  setFormData({ ...formData, price: parseInt(e.target.value) || 0 })
                }
                placeholder="35000"
                className="rounded-full"
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="category" className="text-sm font-medium text-gray-700">
                分類 <span className="text-red-500">*</span>
              </Label>
              <Select
                value={formData.category}
                onValueChange={(value: TourFormData["category"]) =>
                  setFormData({ ...formData, category: value })
                }
              >
                <SelectTrigger className="rounded-full">
                  <SelectValue placeholder="選擇分類" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="group">團體旅遊</SelectItem>
                  <SelectItem value="custom">客製化行程</SelectItem>
                  <SelectItem value="package">自由行套裝</SelectItem>
                  <SelectItem value="cruise">郵輪旅遊</SelectItem>
                  <SelectItem value="theme">主題旅遊</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="status" className="text-sm font-medium text-gray-700">
                狀態 <span className="text-red-500">*</span>
              </Label>
              <Select
                value={formData.status}
                onValueChange={(value: TourFormData["status"]) =>
                  setFormData({ ...formData, status: value })
                }
              >
                <SelectTrigger className="rounded-full">
                  <SelectValue placeholder="選擇狀態" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="active">上架中</SelectItem>
                  <SelectItem value="inactive">已下架</SelectItem>
                  <SelectItem value="soldout">已售完</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid gap-2">
            <Label htmlFor="imageUrl" className="text-sm font-medium text-gray-700">
              圖片網址
            </Label>
            <Input
              id="imageUrl"
              value={formData.imageUrl}
              onChange={(e) =>
                setFormData({ ...formData, imageUrl: e.target.value })
              }
              placeholder="https://example.com/image.jpg"
              className="rounded-full"
            />
            <p className="text-xs text-gray-500">建議尺寸：1200x800px，支援 JPG/PNG 格式</p>
          </div>
        </div>
      </div>

      {/* 詳細描述區塊 */}
      <div className="space-y-4">
        <div className="flex items-center gap-2 pb-2 border-b border-gray-200">
          <div className="h-1.5 w-1.5 rounded-full bg-black"></div>
          <h3 className="text-sm font-semibold text-gray-900">詳細描述</h3>
        </div>

        <div className="grid gap-4">
          <div className="grid gap-2">
            <Label htmlFor="description" className="text-sm font-medium text-gray-700">
              行程描述 <span className="text-red-500">*</span>
            </Label>
            <Textarea
              id="description"
              value={formData.description}
              onChange={(e) =>
                setFormData({ ...formData, description: e.target.value })
              }
              placeholder="請輸入行程的整體描述，包含主要特色和適合對象..."
              rows={4}
              className="rounded-2xl resize-none"
            />
          </div>

          <div className="grid gap-2">
            <Label htmlFor="highlights" className="text-sm font-medium text-gray-700">
              行程亮點
            </Label>
            <Textarea
              id="highlights"
              value={formData.highlights}
              onChange={(e) =>
                setFormData({ ...formData, highlights: e.target.value })
              }
              placeholder="每行一個亮點，例：\n- 參觀東京鐵塔\n- 體驗清水寺和服\n- 品嚐正宗懷石料理"
              rows={4}
              className="rounded-2xl resize-none"
            />
            <p className="text-xs text-gray-500">建議使用條列式格式，每行一個亮點</p>
          </div>
        </div>
      </div>

      {/* 費用說明區塊 */}
      <div className="space-y-4">
        <div className="flex items-center gap-2 pb-2 border-b border-gray-200">
          <div className="h-1.5 w-1.5 rounded-full bg-black"></div>
          <h3 className="text-sm font-semibold text-gray-900">費用說明</h3>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div className="grid gap-2">
            <Label htmlFor="includes" className="text-sm font-medium text-gray-700">
              費用包含
            </Label>
            <Textarea
              id="includes"
              value={formData.includes}
              onChange={(e) =>
                setFormData({ ...formData, includes: e.target.value })
              }
              placeholder="每行一項，例：\n- 來回經濟艙機票\n- 4 晚住宿（雙人房）\n- 每日早餐"
              rows={4}
              className="rounded-2xl resize-none"
            />
            <p className="text-xs text-gray-500">列出包含在團費內的服務項目</p>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="excludes" className="text-sm font-medium text-gray-700">
              費用不含
            </Label>
            <Textarea
              id="excludes"
              value={formData.excludes}
              onChange={(e) =>
                setFormData({ ...formData, excludes: e.target.value })
              }
              placeholder="每行一項，例：\n- 簽證費用\n- 個人旅遊保險\n- 導遊小費"
              rows={4}
              className="rounded-2xl resize-none"
            />
            <p className="text-xs text-gray-500">列出不包含在團費內的項目</p>
          </div>
        </div>
      </div>

      {/* 其他設定區塊 */}
      <div className="space-y-4">
        <div className="flex items-center gap-2 pb-2 border-b border-gray-200">
          <div className="h-1.5 w-1.5 rounded-full bg-black"></div>
          <h3 className="text-sm font-semibold text-gray-900">其他設定</h3>
        </div>

        <div className="flex items-center gap-3 p-4 bg-gray-50 rounded-2xl">
          <input
            type="checkbox"
            id="featured"
            checked={formData.featured === 1}
            onChange={(e) =>
              setFormData({ ...formData, featured: e.target.checked ? 1 : 0 })
            }
            className="h-5 w-5 rounded border-gray-300 text-yellow-500 focus:ring-yellow-500"
          />
          <div>
            <Label htmlFor="featured" className="cursor-pointer text-sm font-medium text-gray-900">
              設為精選行程
            </Label>
            <p className="text-xs text-gray-500 mt-0.5">精選行程將顯示在首頁和熱門推薦區域</p>
          </div>
        </div>
      </div>
    </div>
  );
}

// Helper functions
function getCategoryLabel(category: string) {
  const labels: Record<string, string> = {
    group: "團體旅遊",
    custom: "客製化行程",
    package: "自由行套裝",
    cruise: "郵輪旅遊",
    theme: "主題旅遊",
  };
  return labels[category] || category;
}

function getStatusLabel(status: string) {
  const labels: Record<string, string> = {
    active: "上架中",
    inactive: "已下架",
    soldout: "已售完",
  };
  return labels[status] || status;
}
