import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Edit, Loader2, Plus, Sparkles, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type TourFormData = {
  title: string;
  destination: string;
  destinationCountry: string;
  destinationCity: string;
  description: string;
  duration: number;
  price: number;
  imageUrl?: string;
  category: "group" | "custom" | "package" | "cruise" | "theme";
  status: "active" | "inactive" | "soldout";
  featured: number;
  maxParticipants?: number;
  highlights?: string;
  includes?: string;
  excludes?: string;
};

export default function ToursTab() {
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [isBatchDeleteDialogOpen, setIsBatchDeleteDialogOpen] = useState(false);
  const [isAutoGenerateDialogOpen, setIsAutoGenerateDialogOpen] = useState(false);
  const [isPreviewDialogOpen, setIsPreviewDialogOpen] = useState(false);
  const [autoGenerateUrl, setAutoGenerateUrl] = useState("");
  const [generatedTourData, setGeneratedTourData] = useState<any>(null);
  const [selectedTourId, setSelectedTourId] = useState<number | null>(null);
  const [selectedTourIds, setSelectedTourIds] = useState<number[]>([]);
  const [formData, setFormData] = useState<TourFormData>({
    title: "",
    destination: "",
    destinationCountry: "",
    destinationCity: "",
    description: "",
    duration: 1,
    price: 0,
    imageUrl: "",
    category: "group",
    status: "active",
    featured: 0,
    maxParticipants: undefined,
    highlights: "",
    includes: "",
    excludes: "",
  });

  const utils = trpc.useUtils();
  const { data: tours, isLoading: toursLoading } = trpc.tours.list.useQuery();
  
  const createTourMutation = trpc.tours.create.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      setIsCreateDialogOpen(false);
      resetForm();
      toast.success("行程已成功建立");
    },
    onError: (error) => {
      toast.error(`建立失敗：${error.message}`);
    },
  });

  const updateTourMutation = trpc.tours.update.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      setIsEditDialogOpen(false);
      resetForm();
      toast.success("行程已成功更新");
    },
    onError: (error) => {
      toast.error(`更新失敗：${error.message}`);
    },
  });

  const deleteTourMutation = trpc.tours.delete.useMutation({
    onSuccess: () => {
      utils.tours.list.invalidate();
      setIsDeleteDialogOpen(false);
      setSelectedTourId(null);
      toast.success("行程已成功刪除");
    },
    onError: (error) => {
      toast.error(`刪除失敗：${error.message}`);
    },
  });

  const batchDeleteToursMutation = trpc.tours.batchDelete.useMutation({
    onSuccess: (data) => {
      utils.tours.list.invalidate();
      setIsBatchDeleteDialogOpen(false);
      setSelectedTourIds([]);
      toast.success(`已成功刪除 ${data.deletedCount} 個行程`);
    },
    onError: (error) => {
      toast.error(`批量刪除失敗：${error.message}`);
    },
  });

  const autoGenerateMutation = trpc.tours.autoGenerate.useMutation({
    onSuccess: (result) => {
      if (result.success && result.data) {
        setGeneratedTourData(result.data);
        setIsAutoGenerateDialogOpen(false);
        setIsPreviewDialogOpen(true);
        toast.success("行程資訊提取成功！請檢視並確認");
      }
    },
    onError: (error) => {
      toast.error(`自動生成失敗：${error.message}`);
    },
  });

  const handleAutoGenerate = () => {
    if (!autoGenerateUrl.trim()) {
      toast.error("請輸入行程網址");
      return;
    }
    autoGenerateMutation.mutate({ url: autoGenerateUrl });
  };

  const handleConfirmGeneratedTour = () => {
    if (generatedTourData) {
      // Prepare data for creation
      const tourData = {
        title: generatedTourData.title,
        destination: generatedTourData.destination,
        destinationCountry: generatedTourData.destinationCountry || "未指定",
        destinationCity: generatedTourData.destinationCity || "未指定",
        description: generatedTourData.description,
        duration: generatedTourData.duration,
        price: generatedTourData.price,
        imageUrl: generatedTourData.imageUrl,
        category: "group" as const,
        status: "active" as const,
        featured: 0,
        highlights: generatedTourData.highlights,
        includes: generatedTourData.includes,
        excludes: generatedTourData.excludes,
        // New enhanced fields
        productCode: generatedTourData.productCode,
        promotionText: generatedTourData.promotionText,
        tags: generatedTourData.tags,
        departureCountry: generatedTourData.departureCountry,
        departureCity: generatedTourData.departureCity,
        departureAirportCode: generatedTourData.departureAirportCode,
        departureAirportName: generatedTourData.departureAirportName,
        destinationRegion: generatedTourData.destinationRegion,
        destinationAirportCode: generatedTourData.destinationAirportCode,
        destinationAirportName: generatedTourData.destinationAirportName,
        destinationDescription: generatedTourData.destinationDescription,
        nights: generatedTourData.nights,
        priceUnit: generatedTourData.priceUnit,
        availableSeats: generatedTourData.availableSeats,
        outboundAirline: generatedTourData.outboundAirline,
        outboundFlightNo: generatedTourData.outboundFlightNo,
        outboundDepartureTime: generatedTourData.outboundDepartureTime,
        outboundArrivalTime: generatedTourData.outboundArrivalTime,
        outboundFlightDuration: generatedTourData.outboundFlightDuration,
        inboundAirline: generatedTourData.inboundAirline,
        inboundFlightNo: generatedTourData.inboundFlightNo,
        inboundDepartureTime: generatedTourData.inboundDepartureTime,
        inboundArrivalTime: generatedTourData.inboundArrivalTime,
        inboundFlightDuration: generatedTourData.inboundFlightDuration,
        hotelName: generatedTourData.hotelName,
        hotelGrade: generatedTourData.hotelGrade,
        hotelNights: generatedTourData.hotelNights,
        hotelLocation: generatedTourData.hotelLocation,
        hotelDescription: generatedTourData.hotelDescription,
        hotelFacilities: generatedTourData.hotelFacilities,
        hotelRoomType: generatedTourData.hotelRoomType,
        hotelRoomSize: generatedTourData.hotelRoomSize,
        hotelCheckIn: generatedTourData.hotelCheckIn,
        hotelCheckOut: generatedTourData.hotelCheckOut,
        hotelSpecialOffers: generatedTourData.hotelSpecialOffers,
        hotelWebsite: generatedTourData.hotelWebsite,
        attractions: generatedTourData.attractions,
        dailyItinerary: generatedTourData.dailyItinerary,
        optionalTours: generatedTourData.optionalTours,
        specialReminders: generatedTourData.specialReminders,
        notes: generatedTourData.notes,
        safetyGuidelines: generatedTourData.safetyGuidelines,
        flightRules: generatedTourData.flightRules,
        sourceUrl: generatedTourData.sourceUrl,
        isAutoGenerated: 1,
        airline: generatedTourData.airline,
      };

      createTourMutation.mutate(tourData);
      setIsPreviewDialogOpen(false);
      setGeneratedTourData(null);
      setAutoGenerateUrl("");
    }
  };

  const resetForm = () => {
    setFormData({
      title: "",
      destination: "",
      destinationCountry: "",
      destinationCity: "",
      description: "",
      duration: 1,
      price: 0,
      imageUrl: "",
      category: "group",
      status: "active",
      featured: 0,
      maxParticipants: undefined,
      highlights: "",
      includes: "",
      excludes: "",
    });
  };

  const handleCreate = () => {
    createTourMutation.mutate(formData);
  };

  const handleEdit = (tourId: number) => {
    const tour = tours?.find((t) => t.id === tourId);
    if (tour) {
      setFormData({
        title: tour.title,
        destination: tour.destination,
        destinationCountry: tour.destinationCountry || "",
        destinationCity: tour.destinationCity || "",
        description: tour.description,
        duration: tour.duration,
        price: tour.price,
        imageUrl: tour.imageUrl || "",
        category: tour.category,
        status: tour.status,
        featured: tour.featured,
        maxParticipants: tour.maxParticipants || undefined,
        highlights: tour.highlights || "",
        includes: tour.includes || "",
        excludes: tour.excludes || "",
      });
      setSelectedTourId(tourId);
      setIsEditDialogOpen(true);
    }
  };

  const handleUpdate = () => {
    if (selectedTourId) {
      updateTourMutation.mutate({
        id: selectedTourId,
        ...formData,
      });
    }
  };

  const handleDelete = (tourId: number) => {
    setSelectedTourId(tourId);
    setIsDeleteDialogOpen(true);
  };

  const confirmDelete = () => {
    if (selectedTourId) {
      deleteTourMutation.mutate({ id: selectedTourId });
    }
  };

  const handleSelectTour = (tourId: number, checked: boolean) => {
    if (checked) {
      setSelectedTourIds([...selectedTourIds, tourId]);
    } else {
      setSelectedTourIds(selectedTourIds.filter((id) => id !== tourId));
    }
  };

  const handleSelectAll = (checked: boolean) => {
    if (checked && tours) {
      setSelectedTourIds(tours.map((tour) => tour.id));
    } else {
      setSelectedTourIds([]);
    }
  };

  const handleBatchDelete = () => {
    if (selectedTourIds.length > 0) {
      setIsBatchDeleteDialogOpen(true);
    }
  };

  const confirmBatchDelete = () => {
    if (selectedTourIds.length > 0) {
      batchDeleteToursMutation.mutate({ ids: selectedTourIds });
    }
  };

  const isAllSelected = tours && tours.length > 0 && selectedTourIds.length === tours.length;
  const isSomeSelected = selectedTourIds.length > 0 && selectedTourIds.length < (tours?.length || 0);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">行程管理</h2>
          <p className="text-sm text-gray-600 mt-1">共 {tours?.length || 0} 個行程</p>
        </div>
        <div className="flex items-center gap-3">
          {selectedTourIds.length > 0 && (
            <Button
              onClick={handleBatchDelete}
              variant="outline"
              className="border-red-300 text-red-600 hover:bg-red-50 rounded-full"
            >
              <Trash2 className="h-4 w-4 mr-2" />
              刪除已選 ({selectedTourIds.length})
            </Button>
          )}
          <Button
            onClick={() => {
              setAutoGenerateUrl("");
              setIsAutoGenerateDialogOpen(true);
            }}
            variant="outline"
            className="border-purple-300 text-purple-600 hover:bg-purple-50 rounded-full"
          >
            <Sparkles className="h-4 w-4 mr-2" />
            AI 自動生成
          </Button>
          <Button
            onClick={() => {
              resetForm();
              setIsCreateDialogOpen(true);
            }}
            className="bg-black text-white hover:bg-gray-800 rounded-full"
          >
            <Plus className="h-4 w-4 mr-2" />
            新增行程
          </Button>
        </div>
      </div>

      {/* Tours Table */}
      <div className="bg-white rounded-3xl border-2 border-gray-200 overflow-hidden">
        {toursLoading ? (
          <div className="p-8 text-center">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-black mx-auto mb-2"></div>
            <p className="text-gray-600">載入中...</p>
          </div>
        ) : tours && tours.length > 0 ? (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50 border-b border-gray-200">
                <tr>
                  <th className="px-4 py-3 text-left">
                    <Checkbox
                      checked={isAllSelected}
                      onCheckedChange={handleSelectAll}
                      className="data-[state=indeterminate]:bg-gray-400"
                      data-state={isSomeSelected ? "indeterminate" : isAllSelected ? "checked" : "unchecked"}
                    />
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    ID
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    標題
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    目的地
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    天數
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    價格
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    分類
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    狀態
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                    操作
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {tours.map((tour) => (
                  <tr key={tour.id} className={`hover:bg-gray-50 ${selectedTourIds.includes(tour.id) ? 'bg-blue-50' : ''}`}>
                    <td className="px-4 py-4">
                      <Checkbox
                        checked={selectedTourIds.includes(tour.id)}
                        onCheckedChange={(checked) => handleSelectTour(tour.id, checked as boolean)}
                      />
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {tour.id}
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-900">{tour.title}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {tour.destination}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {tour.duration} 天
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      NT$ {tour.price.toLocaleString()}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {getCategoryLabel(tour.category)}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span
                        className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${
                          tour.status === "active"
                            ? "bg-green-100 text-green-800"
                            : tour.status === "soldout"
                              ? "bg-red-100 text-red-800"
                              : "bg-gray-100 text-gray-800"
                        }`}
                      >
                        {getStatusLabel(tour.status)}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleEdit(tour.id)}
                        className="mr-2 rounded-full"
                      >
                        <Edit className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleDelete(tour.id)}
                        className="text-red-600 hover:text-red-700 rounded-full"
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="p-8 text-center">
            <p className="text-gray-600">尚無行程資料</p>
          </div>
        )}
      </div>

      {/* Create Dialog */}
      <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto rounded-3xl">
          <DialogHeader>
            <DialogTitle>新增行程</DialogTitle>
            <DialogDescription>填寫以下資訊以建立新的旅遊行程</DialogDescription>
          </DialogHeader>
          <TourForm formData={formData} setFormData={setFormData} />
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsCreateDialogOpen(false)}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              onClick={handleCreate}
              disabled={createTourMutation.isPending}
              className="bg-black text-white hover:bg-gray-800 rounded-full"
            >
              {createTourMutation.isPending ? "建立中..." : "建立"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Edit Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto rounded-3xl">
          <DialogHeader>
            <DialogTitle>編輯行程</DialogTitle>
            <DialogDescription>修改行程資訊</DialogDescription>
          </DialogHeader>
          <TourForm formData={formData} setFormData={setFormData} />
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsEditDialogOpen(false)}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              onClick={handleUpdate}
              disabled={updateTourMutation.isPending}
              className="bg-black text-white hover:bg-gray-800 rounded-full"
            >
              {updateTourMutation.isPending ? "更新中..." : "更新"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <DialogContent className="rounded-3xl">
          <DialogHeader>
            <DialogTitle>確認刪除</DialogTitle>
            <DialogDescription>
              您確定要刪除這個行程嗎？此操作無法復原。
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsDeleteDialogOpen(false)}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              onClick={confirmDelete}
              disabled={deleteTourMutation.isPending}
              className="bg-red-600 text-white hover:bg-red-700 rounded-full"
            >
              {deleteTourMutation.isPending ? "刪除中..." : "刪除"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Batch Delete Confirmation Dialog */}
      <Dialog open={isBatchDeleteDialogOpen} onOpenChange={setIsBatchDeleteDialogOpen}>
        <DialogContent className="rounded-3xl">
          <DialogHeader>
            <DialogTitle>確認批量刪除</DialogTitle>
            <DialogDescription>
              您確定要刪除選取的 {selectedTourIds.length} 個行程嗎？此操作無法復原。
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsBatchDeleteDialogOpen(false)}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              onClick={confirmBatchDelete}
              disabled={batchDeleteToursMutation.isPending}
              className="bg-red-600 text-white hover:bg-red-700 rounded-full"
            >
              {batchDeleteToursMutation.isPending ? "刪除中..." : `刪除 ${selectedTourIds.length} 個行程`}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Auto Generate Dialog */}
      <Dialog open={isAutoGenerateDialogOpen} onOpenChange={setIsAutoGenerateDialogOpen}>
        <DialogContent className="max-w-lg rounded-3xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-purple-600" />
              AI 自動生成行程
            </DialogTitle>
            <DialogDescription>
              輸入旅遊行程網址，系統將自動提取行程資訊並生成統一格式的行程
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <Label htmlFor="autoGenerateUrl">行程網址</Label>
              <Input
                id="autoGenerateUrl"
                value={autoGenerateUrl}
                onChange={(e) => setAutoGenerateUrl(e.target.value)}
                placeholder="https://travel.example.com/tour/..."
                className="rounded-full"
              />
            </div>
            <p className="text-sm text-gray-500">
              支援雄獅旅遊、可樂旅遊、雄鸟旅遊等主流旅遊網站的行程頁面
            </p>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsAutoGenerateDialogOpen(false)}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              onClick={handleAutoGenerate}
              disabled={autoGenerateMutation.isPending}
              className="bg-purple-600 text-white hover:bg-purple-700 rounded-full"
            >
              {autoGenerateMutation.isPending ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  提取中...
                </>
              ) : (
                <>
                  <Sparkles className="h-4 w-4 mr-2" />
                  開始提取
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Preview Generated Tour Dialog */}
      <Dialog open={isPreviewDialogOpen} onOpenChange={setIsPreviewDialogOpen}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto rounded-3xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-purple-600" />
              行程資訊預覽
            </DialogTitle>
            <DialogDescription>
              請檢查自動提取的行程資訊，確認無誤後即可儲存
            </DialogDescription>
          </DialogHeader>
          {generatedTourData && (
            <div className="grid gap-6 py-4">
              {/* Basic Info */}
              <div className="bg-purple-50 rounded-2xl p-4">
                <h3 className="font-semibold text-purple-900 mb-3">基本資訊</h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-gray-500">標題：</span>
                    <span className="ml-2 font-medium">{generatedTourData.title}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">產品代碼：</span>
                    <span className="ml-2">{generatedTourData.productCode || '-'}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">促銷文字：</span>
                    <span className="ml-2 text-red-600">{generatedTourData.promotionText || '-'}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">天數：</span>
                    <span className="ml-2">{generatedTourData.duration} 天 {generatedTourData.nights || (generatedTourData.duration - 1)} 晚</span>
                  </div>
                  <div>
                    <span className="text-gray-500">價格：</span>
                    <span className="ml-2 font-bold text-lg text-green-600">NT$ {generatedTourData.price?.toLocaleString()}</span>
                  </div>
                </div>
              </div>

              {/* Location Info */}
              <div className="bg-blue-50 rounded-2xl p-4">
                <h3 className="font-semibold text-blue-900 mb-3">地點資訊</h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-gray-500">出發國家/城市：</span>
                    <span className="ml-2">{generatedTourData.departureCountry} / {generatedTourData.departureCity}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">出發機場：</span>
                    <span className="ml-2">{generatedTourData.departureAirportCode} {generatedTourData.departureAirportName}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">目的地國家/城市：</span>
                    <span className="ml-2 font-medium">{generatedTourData.destinationCountry} / {generatedTourData.destinationCity}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">目的地機場：</span>
                    <span className="ml-2">{generatedTourData.destinationAirportCode} {generatedTourData.destinationAirportName}</span>
                  </div>
                </div>
              </div>

              {/* Flight Info */}
              <div className="bg-orange-50 rounded-2xl p-4">
                <h3 className="font-semibold text-orange-900 mb-3">航班資訊</h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div className="border-r border-orange-200 pr-4">
                    <p className="font-medium mb-2">去程</p>
                    <p><span className="text-gray-500">航空公司：</span>{generatedTourData.outboundAirline || '-'}</p>
                    <p><span className="text-gray-500">時間：</span>{generatedTourData.outboundDepartureTime} → {generatedTourData.outboundArrivalTime}</p>
                    <p><span className="text-gray-500">飛行時間：</span>{generatedTourData.outboundFlightDuration || '-'}</p>
                  </div>
                  <div className="pl-4">
                    <p className="font-medium mb-2">回程</p>
                    <p><span className="text-gray-500">航空公司：</span>{generatedTourData.inboundAirline || '-'}</p>
                    <p><span className="text-gray-500">時間：</span>{generatedTourData.inboundDepartureTime} → {generatedTourData.inboundArrivalTime}</p>
                    <p><span className="text-gray-500">飛行時間：</span>{generatedTourData.inboundFlightDuration || '-'}</p>
                  </div>
                </div>
              </div>

              {/* Hotel Info */}
              <div className="bg-green-50 rounded-2xl p-4">
                <h3 className="font-semibold text-green-900 mb-3">住宿資訊</h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-gray-500">酒店名稱：</span>
                    <span className="ml-2 font-medium">{generatedTourData.hotelName || '-'}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">酒店等級：</span>
                    <span className="ml-2">{generatedTourData.hotelGrade || '-'}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">位置：</span>
                    <span className="ml-2">{generatedTourData.hotelLocation || '-'}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">入住/退房：</span>
                    <span className="ml-2">{generatedTourData.hotelCheckIn || '-'} / {generatedTourData.hotelCheckOut || '-'}</span>
                  </div>
                </div>
              </div>

              {/* Description */}
              <div className="bg-gray-50 rounded-2xl p-4">
                <h3 className="font-semibold text-gray-900 mb-3">行程描述</h3>
                <p className="text-sm text-gray-700 whitespace-pre-wrap">{generatedTourData.description}</p>
              </div>

              {/* Source URL */}
              <div className="text-xs text-gray-400">
                來源：<a href={generatedTourData.sourceUrl} target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">{generatedTourData.sourceUrl}</a>
              </div>
            </div>
          )}
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setIsPreviewDialogOpen(false);
                setGeneratedTourData(null);
              }}
              className="rounded-full"
            >
              取消
            </Button>
            <Button
              onClick={handleConfirmGeneratedTour}
              disabled={createTourMutation.isPending}
              className="bg-purple-600 text-white hover:bg-purple-700 rounded-full"
            >
              {createTourMutation.isPending ? "儲存中..." : "確認儲存"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// Tour Form Component
function TourForm({
  formData,
  setFormData,
}: {
  formData: TourFormData;
  setFormData: React.Dispatch<React.SetStateAction<TourFormData>>;
}) {
  return (
    <div className="grid gap-4 py-4">
      <div className="grid gap-2">
        <Label htmlFor="title">行程標題 *</Label>
        <Input
          id="title"
          value={formData.title}
          onChange={(e) =>
            setFormData({ ...formData, title: e.target.value })
          }
          placeholder="例：東京賞櫻 5 日遊"
          className="rounded-full"
        />
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div className="grid gap-2">
          <Label htmlFor="destination">目的地 *</Label>
          <Input
            id="destination"
            value={formData.destination}
            onChange={(e) =>
              setFormData({ ...formData, destination: e.target.value })
            }
            placeholder="例：日本"
            className="rounded-full"
          />
        </div>
        <div className="grid gap-2">
          <Label htmlFor="duration">天數 *</Label>
          <Input
            id="duration"
            type="number"
            min={1}
            value={formData.duration}
            onChange={(e) =>
              setFormData({ ...formData, duration: parseInt(e.target.value) || 1 })
            }
            className="rounded-full"
          />
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div className="grid gap-2">
          <Label htmlFor="price">價格 (NT$) *</Label>
          <Input
            id="price"
            type="number"
            min={0}
            value={formData.price}
            onChange={(e) =>
              setFormData({ ...formData, price: parseInt(e.target.value) || 0 })
            }
            className="rounded-full"
          />
        </div>
        <div className="grid gap-2">
          <Label htmlFor="maxParticipants">人數上限</Label>
          <Input
            id="maxParticipants"
            type="number"
            min={1}
            value={formData.maxParticipants || ""}
            onChange={(e) =>
              setFormData({
                ...formData,
                maxParticipants: e.target.value ? parseInt(e.target.value) : undefined,
              })
            }
            placeholder="不限"
            className="rounded-full"
          />
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div className="grid gap-2">
          <Label htmlFor="category">分類 *</Label>
          <Select
            value={formData.category}
            onValueChange={(value: TourFormData["category"]) =>
              setFormData({ ...formData, category: value })
            }
          >
            <SelectTrigger className="rounded-full">
              <SelectValue placeholder="選擇分類" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="group">團體旅遊</SelectItem>
              <SelectItem value="custom">客製化行程</SelectItem>
              <SelectItem value="package">自由行套裝</SelectItem>
              <SelectItem value="cruise">郵輪旅遊</SelectItem>
              <SelectItem value="theme">主題旅遊</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="grid gap-2">
          <Label htmlFor="status">狀態 *</Label>
          <Select
            value={formData.status}
            onValueChange={(value: TourFormData["status"]) =>
              setFormData({ ...formData, status: value })
            }
          >
            <SelectTrigger className="rounded-full">
              <SelectValue placeholder="選擇狀態" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="active">上架中</SelectItem>
              <SelectItem value="inactive">已下架</SelectItem>
              <SelectItem value="soldout">已售完</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      <div className="grid gap-2">
        <Label htmlFor="imageUrl">圖片網址</Label>
        <Input
          id="imageUrl"
          value={formData.imageUrl}
          onChange={(e) =>
            setFormData({ ...formData, imageUrl: e.target.value })
          }
          placeholder="https://example.com/image.jpg"
          className="rounded-full"
        />
      </div>

      <div className="grid gap-2">
        <Label htmlFor="description">行程描述 *</Label>
        <Textarea
          id="description"
          value={formData.description}
          onChange={(e) =>
            setFormData({ ...formData, description: e.target.value })
          }
          placeholder="請輸入行程描述..."
          rows={3}
          className="rounded-2xl"
        />
      </div>

      <div className="grid gap-2">
        <Label htmlFor="highlights">行程亮點</Label>
        <Textarea
          id="highlights"
          value={formData.highlights}
          onChange={(e) =>
            setFormData({ ...formData, highlights: e.target.value })
          }
          placeholder="每行一個亮點..."
          rows={3}
          className="rounded-2xl"
        />
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div className="grid gap-2">
          <Label htmlFor="includes">費用包含</Label>
          <Textarea
            id="includes"
            value={formData.includes}
            onChange={(e) =>
              setFormData({ ...formData, includes: e.target.value })
            }
            placeholder="每行一項..."
            rows={3}
            className="rounded-2xl"
          />
        </div>
        <div className="grid gap-2">
          <Label htmlFor="excludes">費用不含</Label>
          <Textarea
            id="excludes"
            value={formData.excludes}
            onChange={(e) =>
              setFormData({ ...formData, excludes: e.target.value })
            }
            placeholder="每行一項..."
            rows={3}
            className="rounded-2xl"
          />
        </div>
      </div>

      <div className="flex items-center gap-2">
        <input
          type="checkbox"
          id="featured"
          checked={formData.featured === 1}
          onChange={(e) =>
            setFormData({ ...formData, featured: e.target.checked ? 1 : 0 })
          }
          className="h-4 w-4 rounded border-gray-300"
        />
        <Label htmlFor="featured" className="cursor-pointer">
          設為精選行程
        </Label>
      </div>
    </div>
  );
}

// Helper functions
function getCategoryLabel(category: string) {
  const labels: Record<string, string> = {
    group: "團體旅遊",
    custom: "客製化行程",
    package: "自由行套裝",
    cruise: "郵輪旅遊",
    theme: "主題旅遊",
  };
  return labels[category] || category;
}

function getStatusLabel(status: string) {
  const labels: Record<string, string> = {
    active: "上架中",
    inactive: "已下架",
    soldout: "已售完",
  };
  return labels[status] || status;
}
